/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type { AgentListResponse as AgentListResponse$Import } from "./models/agents/agent-list-response.js";
import type { AgentTool as AgentTool$Import } from "./models/agents/agent-tool.js";
import type { Agent as Agent$Import } from "./models/agents/agent.js";
import type { CreateEnvironmentRequest as CreateEnvironmentRequest$Import } from "./models/environments/create-environment-request.js";
import type { EnvironmentFile as EnvironmentFile$Import } from "./models/environments/environment-file.js";
import type { Environment as Environment$Import } from "./models/environments/environment.js";
import type { GetEnvironmentFilesResponse as GetEnvironmentFilesResponse$Import } from "./models/environments/get-environment-files-response.js";
import type { ListEnvironmentsResponse as ListEnvironmentsResponse$Import } from "./models/environments/list-environments-response.js";
import type { AllowedTools as AllowedTools$Import } from "./models/interactions/allowed-tools.js";
import type { Annotation as Annotation$Import } from "./models/interactions/annotation.js";
import type { AntigravityAgentConfig as AntigravityAgentConfig$Import } from "./models/interactions/antigravity-agent-config.js";
import type { ArgumentsDelta as ArgumentsDelta$Import } from "./models/interactions/arguments-delta.js";
import type { AudioContent as AudioContent$Import } from "./models/interactions/audio-content.js";
import type { AudioDelta as AudioDelta$Import } from "./models/interactions/audio-delta.js";
import type { AudioResponseFormat as AudioResponseFormat$Import } from "./models/interactions/audio-response-format.js";
import type { CodeExecutionCallArguments as CodeExecutionCallArguments$Import } from "./models/interactions/code-execution-call-arguments.js";
import type { CodeExecutionCallDelta as CodeExecutionCallDelta$Import } from "./models/interactions/code-execution-call-delta.js";
import type { CodeExecutionCallStep as CodeExecutionCallStep$Import } from "./models/interactions/code-execution-call-step.js";
import type { CodeExecutionResultDelta as CodeExecutionResultDelta$Import } from "./models/interactions/code-execution-result-delta.js";
import type { CodeExecutionResultStep as CodeExecutionResultStep$Import } from "./models/interactions/code-execution-result-step.js";
import type { CodeExecution as CodeExecution$Import } from "./models/interactions/code-execution.js";
import type { CodeMenderAgentConfig as CodeMenderAgentConfig$Import } from "./models/interactions/code-mender-agent-config.js";
import type { ComputerUse as ComputerUse$Import } from "./models/interactions/computer-use.js";
import type { Content as Content$Import } from "./models/interactions/content.js";
import type { CreateAgentInteraction as CreateAgentInteraction$Import } from "./models/interactions/create-agent-interaction.js";
import type { CreateModelInteraction as CreateModelInteraction$Import } from "./models/interactions/create-model-interaction.js";
import type { DeepResearchAgentConfig as DeepResearchAgentConfig$Import } from "./models/interactions/deep-research-agent-config.js";
import type { DocumentContent as DocumentContent$Import } from "./models/interactions/document-content.js";
import type { DocumentDelta as DocumentDelta$Import } from "./models/interactions/document-delta.js";
import type { DynamicAgentConfig as DynamicAgentConfig$Import } from "./models/interactions/dynamic-agent-config.js";
import type { Empty as Empty$Import } from "./models/interactions/empty.js";
import type { Allowlist as Allowlist$Import } from "./models/interactions/environment-network-egress-allowlist.js";
import type { Environment as Environment$Import2 } from "./models/interactions/environment.js";
import type { ErrorEvent as ErrorEvent$Import } from "./models/interactions/error-event.js";
import type { ErrorT as ErrorT$Import } from "./models/interactions/error.js";
import type { FileCitation as FileCitation$Import } from "./models/interactions/file-citation.js";
import type { FileContent as FileContent$Import } from "./models/interactions/file-content.js";
import type { FileSearchCallDelta as FileSearchCallDelta$Import } from "./models/interactions/file-search-call-delta.js";
import type { FileSearchCallStep as FileSearchCallStep$Import } from "./models/interactions/file-search-call-step.js";
import type { FileSearchResultDelta as FileSearchResultDelta$Import } from "./models/interactions/file-search-result-delta.js";
import type { FileSearchResultStep as FileSearchResultStep$Import } from "./models/interactions/file-search-result-step.js";
import type { FileSearch as FileSearch$Import } from "./models/interactions/file-search.js";
import type { FindRequest as FindRequest$Import } from "./models/interactions/find-request.js";
import type { FixRequest as FixRequest$Import } from "./models/interactions/fix-request.js";
import type { FunctionCallStep as FunctionCallStep$Import } from "./models/interactions/function-call-step.js";
import type { FunctionResultDelta as FunctionResultDelta$Import } from "./models/interactions/function-result-delta.js";
import type { FunctionResultStep as FunctionResultStep$Import } from "./models/interactions/function-result-step.js";
import type { FunctionT as FunctionT$Import } from "./models/interactions/function.js";
import type { GenerationConfig as GenerationConfig$Import } from "./models/interactions/generation-config.js";
import type { GoogleMapsCallArguments as GoogleMapsCallArguments$Import } from "./models/interactions/google-maps-call-arguments.js";
import type { GoogleMapsCallDelta as GoogleMapsCallDelta$Import } from "./models/interactions/google-maps-call-delta.js";
import type { GoogleMapsCallStep as GoogleMapsCallStep$Import } from "./models/interactions/google-maps-call-step.js";
import type { GoogleMapsResultDelta as GoogleMapsResultDelta$Import } from "./models/interactions/google-maps-result-delta.js";
import type { GoogleMapsResultPlaces as GoogleMapsResultPlaces$Import } from "./models/interactions/google-maps-result-places.js";
import type { GoogleMapsResultStep as GoogleMapsResultStep$Import } from "./models/interactions/google-maps-result-step.js";
import type { GoogleMapsResult as GoogleMapsResult$Import } from "./models/interactions/google-maps-result.js";
import type { GoogleMaps as GoogleMaps$Import } from "./models/interactions/google-maps.js";
import type { GoogleSearchCallArguments as GoogleSearchCallArguments$Import } from "./models/interactions/google-search-call-arguments.js";
import type { GoogleSearchCallDelta as GoogleSearchCallDelta$Import } from "./models/interactions/google-search-call-delta.js";
import type { GoogleSearchCallStep as GoogleSearchCallStep$Import } from "./models/interactions/google-search-call-step.js";
import type { GoogleSearchResultDelta as GoogleSearchResultDelta$Import } from "./models/interactions/google-search-result-delta.js";
import type { GoogleSearchResultStep as GoogleSearchResultStep$Import } from "./models/interactions/google-search-result-step.js";
import type { GoogleSearchResult as GoogleSearchResult$Import } from "./models/interactions/google-search-result.js";
import type { GoogleSearch as GoogleSearch$Import } from "./models/interactions/google-search.js";
import type { GroundingToolCount as GroundingToolCount$Import } from "./models/interactions/grounding-tool-count.js";
import type { HarmCategory as HarmCategory$Import } from "./models/interactions/harm-category.js";
import type { ImageConfig as ImageConfig$Import } from "./models/interactions/image-config.js";
import type { ImageContent as ImageContent$Import } from "./models/interactions/image-content.js";
import type { ImageDelta as ImageDelta$Import } from "./models/interactions/image-delta.js";
import type { ImageResponseFormat as ImageResponseFormat$Import } from "./models/interactions/image-response-format.js";
import type { InteractionCompletedEvent as InteractionCompletedEvent$Import } from "./models/interactions/interaction-completed-event.js";
import type { InteractionCreatedEvent as InteractionCreatedEvent$Import } from "./models/interactions/interaction-created-event.js";
import type { InteractionSSEEvent as InteractionSSEEvent$Import } from "./models/interactions/interaction-sse-event.js";
import type { InteractionStatusUpdate as InteractionStatusUpdate$Import } from "./models/interactions/interaction-status-update.js";
import type { Interaction as Interaction$Import } from "./models/interactions/interaction.js";
import type { MCPServerToolCallDelta as MCPServerToolCallDelta$Import } from "./models/interactions/mcp-server-tool-call-delta.js";
import type { MCPServerToolCallStep as MCPServerToolCallStep$Import } from "./models/interactions/mcp-server-tool-call-step.js";
import type { MCPServerToolResultDelta as MCPServerToolResultDelta$Import } from "./models/interactions/mcp-server-tool-result-delta.js";
import type { MCPServerToolResultStep as MCPServerToolResultStep$Import } from "./models/interactions/mcp-server-tool-result-step.js";
import type { MCPServer as MCPServer$Import } from "./models/interactions/mcp-server.js";
import type { ModalityTokens as ModalityTokens$Import } from "./models/interactions/modality-tokens.js";
import type { ModelOutputStep as ModelOutputStep$Import } from "./models/interactions/model-output-step.js";
import type { Model as Model$Import } from "./models/interactions/model.js";
import type { PlaceCitation as PlaceCitation$Import } from "./models/interactions/place-citation.js";
import type { ProcessingCallDelta as ProcessingCallDelta$Import } from "./models/interactions/processing-call-delta.js";
import type { ProcessingCallStep as ProcessingCallStep$Import } from "./models/interactions/processing-call-step.js";
import type { ProcessingResultDelta as ProcessingResultDelta$Import } from "./models/interactions/processing-result-delta.js";
import type { ProcessingResultStep as ProcessingResultStep$Import } from "./models/interactions/processing-result-step.js";
import type { RetrievalCallArguments as RetrievalCallArguments$Import } from "./models/interactions/retrieval-call-arguments.js";
import type { RetrievalCallDelta as RetrievalCallDelta$Import } from "./models/interactions/retrieval-call-delta.js";
import type { RetrievalCallStep as RetrievalCallStep$Import } from "./models/interactions/retrieval-call-step.js";
import type { RetrievalResultDelta as RetrievalResultDelta$Import } from "./models/interactions/retrieval-result-delta.js";
import type { RetrievalResultStep as RetrievalResultStep$Import } from "./models/interactions/retrieval-result-step.js";
import type { Retrieval as Retrieval$Import } from "./models/interactions/retrieval.js";
import type { ReviewSnippet as ReviewSnippet$Import } from "./models/interactions/review-snippet.js";
import type { SafetySetting as SafetySetting$Import } from "./models/interactions/safety-setting.js";
import type { SessionConfig as SessionConfig$Import } from "./models/interactions/session-config.js";
import type { SmartTranscriptionMode as SmartTranscriptionMode$Import } from "./models/interactions/smart-transcription-mode.js";
import type { Source as Source$Import } from "./models/interactions/source.js";
import type { SpeechConfig as SpeechConfig$Import } from "./models/interactions/speech-config.js";
import type { StaticMediaProcessing as StaticMediaProcessing$Import } from "./models/interactions/static-media-processing.js";
import type { StepDeltaMetadata as StepDeltaMetadata$Import } from "./models/interactions/step-delta-metadata.js";
import type { StepDelta as StepDelta$Import } from "./models/interactions/step-delta.js";
import type { StepStart as StepStart$Import } from "./models/interactions/step-start.js";
import type { StepStop as StepStop$Import } from "./models/interactions/step-stop.js";
import type { Step as Step$Import } from "./models/interactions/step.js";
import type { TextAnnotationDelta as TextAnnotationDelta$Import } from "./models/interactions/text-annotation-delta.js";
import type { TextContent as TextContent$Import } from "./models/interactions/text-content.js";
import type { TextDelta as TextDelta$Import } from "./models/interactions/text-delta.js";
import type { TextResponseFormat as TextResponseFormat$Import } from "./models/interactions/text-response-format.js";
import type { ThinkingLevel as ThinkingLevel$Import } from "./models/interactions/thinking-level.js";
import type { ThoughtSignatureDelta as ThoughtSignatureDelta$Import } from "./models/interactions/thought-signature-delta.js";
import type { ThoughtStep as ThoughtStep$Import } from "./models/interactions/thought-step.js";
import type { ThoughtSummaryDelta as ThoughtSummaryDelta$Import } from "./models/interactions/thought-summary-delta.js";
import type { ToolChoiceConfig as ToolChoiceConfig$Import } from "./models/interactions/tool-choice-config.js";
import type { ToolChoiceType as ToolChoiceType$Import } from "./models/interactions/tool-choice-type.js";
import type { Tool as Tool$Import } from "./models/interactions/tool.js";
import type { TranscriptionConfig as TranscriptionConfig$Import } from "./models/interactions/transcription-config.js";
import type { TranscriptionMode as TranscriptionMode$Import } from "./models/interactions/transcription-mode.js";
import type { URLCitation as URLCitation$Import } from "./models/interactions/url-citation.js";
import type { URLContextCallArguments as URLContextCallArguments$Import } from "./models/interactions/url-context-call-arguments.js";
import type { URLContextCallDelta as URLContextCallDelta$Import } from "./models/interactions/url-context-call-delta.js";
import type { URLContextCallStep as URLContextCallStep$Import } from "./models/interactions/url-context-call-step.js";
import type { URLContextResultDelta as URLContextResultDelta$Import } from "./models/interactions/url-context-result-delta.js";
import type { URLContextResultStep as URLContextResultStep$Import } from "./models/interactions/url-context-result-step.js";
import type { URLContextResult as URLContextResult$Import } from "./models/interactions/url-context-result.js";
import type { URLContext as URLContext$Import } from "./models/interactions/url-context.js";
import type { Usage as Usage$Import } from "./models/interactions/usage.js";
import type { UserInputStep as UserInputStep$Import } from "./models/interactions/user-input-step.js";
import type { VerbatimTranscriptionMode as VerbatimTranscriptionMode$Import } from "./models/interactions/verbatim-transcription-mode.js";
import type { VertexAISearchConfig as VertexAISearchConfig$Import } from "./models/interactions/vertex-ai-search-config.js";
import type { VideoConfig as VideoConfig$Import } from "./models/interactions/video-config.js";
import type { VideoContent as VideoContent$Import } from "./models/interactions/video-content.js";
import type { VideoDelta as VideoDelta$Import } from "./models/interactions/video-delta.js";
import type { VideoResponseFormat as VideoResponseFormat$Import } from "./models/interactions/video-response-format.js";
import type { WebhookConfig as WebhookConfig$Import } from "./models/interactions/webhook-config.js";
import type { WordInfo as WordInfo$Import } from "./models/interactions/word-info.js";
import type {
  CancelInteractionByIdParams as CancelInteractionByIdParams$Import,
  CreateAgentParams as CreateAgentParams$Import,
  CreateInteractionParams as CreateInteractionParams$Import,
  CreateWebhookParams as CreateWebhookParams$Import,
  DeleteAgentParams as DeleteAgentParams$Import,
  DeleteInteractionParams as DeleteInteractionParams$Import,
  DeleteTriggerParams as DeleteTriggerParams$Import,
  DeleteWebhookParams as DeleteWebhookParams$Import,
  GetAgentParams as GetAgentParams$Import,
  GetInteractionByIdParams as GetInteractionByIdParams$Import,
  GetInteractionByIdParamsNonStreaming
    as GetInteractionByIdParamsNonStreaming$Import,
  GetInteractionByIdParamsStreaming as GetInteractionByIdParamsStreaming$Import,
  GetTriggerParams as GetTriggerParams$Import,
  GetWebhookParams as GetWebhookParams$Import,
  ListAgentsParams as ListAgentsParams$Import,
  ListTriggerExecutionsParams as ListTriggerExecutionsParams$Import,
  ListTriggersParams as ListTriggersParams$Import,
  ListWebhooksParams as ListWebhooksParams$Import,
  RunTriggerParams as RunTriggerParams$Import,
  UpdateTriggerParams as UpdateTriggerParams$Import,
} from "./models/operations/method-params.js";
import type { ListTriggerExecutionsResponse as ListTriggerExecutionsResponse$Import } from "./models/triggers/list-trigger-executions-response.js";
import type { ListTriggersResponse as ListTriggersResponse$Import } from "./models/triggers/list-triggers-response.js";
import type { TriggerCreateParams as TriggerCreateParams$Import } from "./models/triggers/trigger-create-params.js";
import type { TriggerExecution as TriggerExecution$Import } from "./models/triggers/trigger-execution.js";
import type { TriggerUpdate as TriggerUpdate$Import } from "./models/triggers/trigger-update.js";
import type { Trigger as Trigger$Import } from "./models/triggers/trigger.js";
import type { PingWebhookRequest as PingWebhookRequest$Import } from "./models/webhooks/ping-webhook-request.js";
import type { RotateSigningSecretRequest as RotateSigningSecretRequest$Import } from "./models/webhooks/rotate-signing-secret-request.js";
import type { SigningSecret as SigningSecret$Import } from "./models/webhooks/signing-secret.js";
import type { WebhookListResponse as WebhookListResponse$Import } from "./models/webhooks/webhook-list-response.js";
import type { WebhookPingResponse as WebhookPingResponse$Import } from "./models/webhooks/webhook-ping-response.js";
import type { WebhookRotateSigningSecretResponse as WebhookRotateSigningSecretResponse$Import } from "./models/webhooks/webhook-rotate-signing-secret-response.js";
import type { WebhookUpdate as WebhookUpdate$Import } from "./models/webhooks/webhook-update.js";
import type {
  Webhook as Webhook$Import,
  WebhookInput as WebhookInput$Import,
} from "./models/webhooks/webhook.js";
type Agent$ = Agent$Import;
type AgentCreateParams$ = CreateAgentParams$Import;
type AgentDeleteParams$ = DeleteAgentParams$Import;
type AgentDeleteResponse$ = Empty$Import;
type AgentGetParams$ = GetAgentParams$Import;
type AgentListParams$ = ListAgentsParams$Import;
type AgentListResponse$ = AgentListResponse$Import;
type AgentTool$ = AgentTool$Import;
type CreateEnvironmentRequest$ = CreateEnvironmentRequest$Import;
type Environment$ = Environment$Import;
type EnvironmentDeleteResponse$ = Empty$Import;
type EnvironmentFile$ = EnvironmentFile$Import;
type EnvironmentListResponse$ = ListEnvironmentsResponse$Import;
type GetEnvironmentFilesResponse$ = GetEnvironmentFilesResponse$Import;
type Allowlist$ = Allowlist$Import;
type Allowlist$2 = Allowlist$Import;
type AllowedTools$ = AllowedTools$Import;
type Annotation$ = Annotation$Import;
type AntigravityAgentConfig$ = AntigravityAgentConfig$Import;
type AudioContent$ = AudioContent$Import;
type AudioResponseFormat$ = AudioResponseFormat$Import;
type CodeExecutionCallArguments$ = CodeExecutionCallArguments$Import;
type CodeExecutionCallStep$ = CodeExecutionCallStep$Import;
type CodeExecutionResultStep$ = CodeExecutionResultStep$Import;
type CodeMenderAgentConfig$ = CodeMenderAgentConfig$Import;
type Content$ = Content$Import;
type CreateAgentInteractionParamsNonStreaming$ = CreateAgentInteraction$Import;
type CreateAgentInteractionParamsStreaming$ = CreateAgentInteraction$Import;
type CreateModelInteractionParamsNonStreaming$ = CreateModelInteraction$Import;
type CreateModelInteractionParamsStreaming$ = CreateModelInteraction$Import;
type DeepResearchAgentConfig$ = DeepResearchAgentConfig$Import;
type DocumentContent$ = DocumentContent$Import;
type DynamicAgentConfig$ = DynamicAgentConfig$Import;
type Environment$2 = Environment$Import2;
type Error$ = ErrorT$Import;
type ErrorEvent$ = ErrorEvent$Import;
type FileCitation$ = FileCitation$Import;
type FileSearchCallStep$ = FileSearchCallStep$Import;
type FileSearchResultStep$ = FileSearchResultStep$Import;
type Function$ = FunctionT$Import;
type FunctionCallStep$ = FunctionCallStep$Import;
type FunctionResultStep$ = FunctionResultStep$Import;
type GenerationConfig$ = GenerationConfig$Import;
type GoogleMapsCallArguments$ = GoogleMapsCallArguments$Import;
type GoogleMapsCallStep$ = GoogleMapsCallStep$Import;
type GoogleMapsResult$ = GoogleMapsResult$Import;
type GoogleMapsResultStep$ = GoogleMapsResultStep$Import;
type GoogleSearchCallArguments$ = GoogleSearchCallArguments$Import;
type GoogleSearchCallStep$ = GoogleSearchCallStep$Import;
type GoogleSearchResult$ = GoogleSearchResult$Import;
type GoogleSearchResultStep$ = GoogleSearchResultStep$Import;
type HarmCategory$ = HarmCategory$Import;
type ImageConfig$ = ImageConfig$Import;
type ImageContent$ = ImageContent$Import;
type ImageResponseFormat$ = ImageResponseFormat$Import;
type Interaction$ = Interaction$Import;
type InteractionCancelParams$ = CancelInteractionByIdParams$Import;
type InteractionCompletedEvent$ = InteractionCompletedEvent$Import;
type InteractionCreateParams$ = CreateInteractionParams$Import;
type InteractionCreatedEvent$ = InteractionCreatedEvent$Import;
type InteractionDeleteParams$ = DeleteInteractionParams$Import;
type InteractionDeleteResponse$ = Empty$Import;
type InteractionGetParams$ = GetInteractionByIdParams$Import;
type InteractionGetParamsNonStreaming$ =
  GetInteractionByIdParamsNonStreaming$Import;
type InteractionGetParamsNonStreaming$2 =
  GetInteractionByIdParamsNonStreaming$Import;
type InteractionGetParamsStreaming$ = GetInteractionByIdParamsStreaming$Import;
type InteractionGetParamsStreaming$2 = GetInteractionByIdParamsStreaming$Import;
type InteractionSSEEvent$ = InteractionSSEEvent$Import;
type InteractionStatusUpdate$ = InteractionStatusUpdate$Import;
type MCPServerToolCallStep$ = MCPServerToolCallStep$Import;
type MCPServerToolResultStep$ = MCPServerToolResultStep$Import;
type Model$ = Model$Import;
type ModelOutputStep$ = ModelOutputStep$Import;
type PlaceCitation$ = PlaceCitation$Import;
type ProcessingCallStep$ = ProcessingCallStep$Import;
type ProcessingResultStep$ = ProcessingResultStep$Import;
type RetrievalCallArguments$ = RetrievalCallArguments$Import;
type RetrievalCallDelta$ = RetrievalCallDelta$Import;
type RetrievalCallStep$ = RetrievalCallStep$Import;
type RetrievalResultDelta$ = RetrievalResultDelta$Import;
type RetrievalResultStep$ = RetrievalResultStep$Import;
type SafetySetting$ = SafetySetting$Import;
type SpeechConfig$ = SpeechConfig$Import;
type Step$ = Step$Import;
type StepDelta$ = StepDelta$Import;
type StepStart$ = StepStart$Import;
type StepStop$ = StepStop$Import;
type TextContent$ = TextContent$Import;
type TextResponseFormat$ = TextResponseFormat$Import;
type ThinkingLevel$ = ThinkingLevel$Import;
type ThoughtStep$ = ThoughtStep$Import;
type Tool$ = Tool$Import;
type ToolChoiceConfig$ = ToolChoiceConfig$Import;
type ToolChoiceType$ = ToolChoiceType$Import;
type TranscriptionConfig$ = TranscriptionConfig$Import;
type TranscriptionMode$ = TranscriptionMode$Import;
type URLCitation$ = URLCitation$Import;
type URLContextCallArguments$ = URLContextCallArguments$Import;
type URLContextCallStep$ = URLContextCallStep$Import;
type URLContextResult$ = URLContextResult$Import;
type URLContextResultStep$ = URLContextResultStep$Import;
type Usage$ = Usage$Import;
type UserInputStep$ = UserInputStep$Import;
type VideoConfig$ = VideoConfig$Import;
type VideoContent$ = VideoContent$Import;
type VideoResponseFormat$ = VideoResponseFormat$Import;
type WebhookConfig$ = WebhookConfig$Import;
type WordInfo$ = WordInfo$Import;
type Arguments$ = CodeExecutionCallArguments$Import;
type FindRequest$ = FindRequest$Import;
type FixRequest$ = FixRequest$Import;
type SessionConfig$ = SessionConfig$Import;
type SourceFile$ = FileContent$Import;
type SourceFile$2 = FileContent$Import;
type Allowlist$3 = Allowlist$Import;
type Source$ = Source$Import;
type Error$2 = ErrorT$Import;
type Arguments$2 = GoogleMapsCallArguments$Import;
type Place$ = GoogleMapsResultPlaces$Import;
type ReviewSnippet$ = ReviewSnippet$Import;
type Result$ = GoogleMapsResult$Import;
type Place$2 = GoogleMapsResultPlaces$Import;
type ReviewSnippet$2 = ReviewSnippet$Import;
type Arguments$3 = GoogleSearchCallArguments$Import;
type Result$2 = GoogleSearchResult$Import;
type ReviewSnippet$3 = ReviewSnippet$Import;
type Arguments$4 = RetrievalCallArguments$Import;
type Arguments$5 = RetrievalCallArguments$Import;
type ArgumentsDelta$ = ArgumentsDelta$Import;
type Audio$ = AudioDelta$Import;
type CodeExecutionCall$ = CodeExecutionCallDelta$Import;
type CodeExecutionResult$ = CodeExecutionResultDelta$Import;
type Document$ = DocumentDelta$Import;
type FileSearchCall$ = FileSearchCallDelta$Import;
type FileSearchResult$ = FileSearchResultDelta$Import;
type FunctionResult$ = FunctionResultDelta$Import;
type GoogleMapsCall$ = GoogleMapsCallDelta$Import;
type GoogleMapsResult$2 = GoogleMapsResultDelta$Import;
type GoogleSearchCall$ = GoogleSearchCallDelta$Import;
type GoogleSearchResult$2 = GoogleSearchResultDelta$Import;
type Image$ = ImageDelta$Import;
type MCPServerToolCall$ = MCPServerToolCallDelta$Import;
type MCPServerToolResult$ = MCPServerToolResultDelta$Import;
type Metadata$ = StepDeltaMetadata$Import;
type ProcessingCall$ = ProcessingCallDelta$Import;
type ProcessingResult$ = ProcessingResultDelta$Import;
type Text$ = TextDelta$Import;
type TextAnnotationDelta$ = TextAnnotationDelta$Import;
type ThoughtSignature$ = ThoughtSignatureDelta$Import;
type ThoughtSummary$ = ThoughtSummaryDelta$Import;
type URLContextCall$ = URLContextCallDelta$Import;
type URLContextResult$2 = URLContextResultDelta$Import;
type Video$ = VideoDelta$Import;
type CodeExecution$ = CodeExecution$Import;
type ComputerUse$ = ComputerUse$Import;
type FileSearch$ = FileSearch$Import;
type GoogleMaps$ = GoogleMaps$Import;
type GoogleSearch$ = GoogleSearch$Import;
type MCPServer$ = MCPServer$Import;
type Retrieval$ = Retrieval$Import;
type URLContext$ = URLContext$Import;
type VertexAISearchConfig$ = VertexAISearchConfig$Import;
type Smart$ = SmartTranscriptionMode$Import;
type Verbatim$ = VerbatimTranscriptionMode$Import;
type Arguments$6 = URLContextCallArguments$Import;
type Result$3 = URLContextResult$Import;
type CachedTokensByModality$ = ModalityTokens$Import;
type GroundingToolCount$ = GroundingToolCount$Import;
type InputTokensByModality$ = ModalityTokens$Import;
type OutputTokensByModality$ = ModalityTokens$Import;
type ToolUseTokensByModality$ = ModalityTokens$Import;
type Static$ = StaticMediaProcessing$Import;
type ListTriggerExecutionsResponse$ = ListTriggerExecutionsResponse$Import;
type ListTriggersResponse$ = ListTriggersResponse$Import;
type Trigger$ = Trigger$Import;
type TriggerCreateParams$ = TriggerCreateParams$Import;
type TriggerDeleteParams$ = DeleteTriggerParams$Import;
type TriggerDeleteResponse$ = Empty$Import;
type TriggerExecution$ = TriggerExecution$Import;
type TriggerGetParams$ = GetTriggerParams$Import;
type TriggerListExecutionsParams$ = ListTriggerExecutionsParams$Import;
type TriggerListExecutionsResponse$ = ListTriggerExecutionsResponse$Import;
type TriggerListParams$ = ListTriggersParams$Import;
type TriggerListResponse$ = ListTriggersResponse$Import;
type TriggerRunParams$ = RunTriggerParams$Import;
type TriggerUpdate$ = TriggerUpdate$Import;
type TriggerUpdateParams$ = UpdateTriggerParams$Import;
type PingWebhookRequest$ = PingWebhookRequest$Import;
type RotateSigningSecretRequest$ = RotateSigningSecretRequest$Import;
type SigningSecret$ = SigningSecret$Import;
type Webhook$ = Webhook$Import;
type WebhookCreateParams$ = CreateWebhookParams$Import;
type WebhookDeleteParams$ = DeleteWebhookParams$Import;
type WebhookDeleteResponse$ = Empty$Import;
type WebhookGetParams$ = GetWebhookParams$Import;
type WebhookInput$ = WebhookInput$Import;
type WebhookListParams$ = ListWebhooksParams$Import;
type WebhookListResponse$ = WebhookListResponse$Import;
type WebhookPingParams$ = PingWebhookRequest$Import;
type WebhookPingResponse$ = WebhookPingResponse$Import;
type WebhookRotateSigningSecretParams$ = RotateSigningSecretRequest$Import;
type WebhookRotateSigningSecretResponse$ =
  WebhookRotateSigningSecretResponse$Import;
type WebhookUpdate$ = WebhookUpdate$Import;
type WebhookUpdateParams$ = WebhookUpdate$Import;
export type Agent = Agent$;
export type AgentCreateParams = AgentCreateParams$;
export type AgentDeleteParams = AgentDeleteParams$;
export type AgentDeleteResponse = AgentDeleteResponse$;
export type AgentGetParams = AgentGetParams$;
export type AgentListParams = AgentListParams$;
export type AgentListResponse = AgentListResponse$;
export type AgentTool = AgentTool$;
export type AllowedTools = AllowedTools$;
export type Allowlist = Allowlist$;
export type Annotation = Annotation$;
export type AntigravityAgentConfig = AntigravityAgentConfig$;
export type Arguments = Arguments$;
export type ArgumentsDelta = ArgumentsDelta$;
export type Audio = Audio$;
export type AudioContent = AudioContent$;
export type AudioResponseFormat = AudioResponseFormat$;
export type CachedTokensByModality = CachedTokensByModality$;
export type CodeExecution = CodeExecution$;
export type CodeExecutionCall = CodeExecutionCall$;
export type CodeExecutionCallArguments = CodeExecutionCallArguments$;
export type CodeExecutionCallStep = CodeExecutionCallStep$;
export type CodeExecutionResult = CodeExecutionResult$;
export type CodeExecutionResultStep = CodeExecutionResultStep$;
export type CodeMenderAgentConfig = CodeMenderAgentConfig$;
export type ComputerUse = ComputerUse$;
export type Content = Content$;
export type CreateAgentInteractionParamsNonStreaming =
  CreateAgentInteractionParamsNonStreaming$;
export type CreateAgentInteractionParamsStreaming =
  CreateAgentInteractionParamsStreaming$;
export type CreateEnvironmentRequest = CreateEnvironmentRequest$;
export type CreateModelInteractionParamsNonStreaming =
  CreateModelInteractionParamsNonStreaming$;
export type CreateModelInteractionParamsStreaming =
  CreateModelInteractionParamsStreaming$;
export type DeepResearchAgentConfig = DeepResearchAgentConfig$;
export type Document = Document$;
export type DocumentContent = DocumentContent$;
export type DynamicAgentConfig = DynamicAgentConfig$;
export type Environment = Environment$;
export type EnvironmentDeleteResponse = EnvironmentDeleteResponse$;
export type EnvironmentFile = EnvironmentFile$;
export type EnvironmentListResponse = EnvironmentListResponse$;
export type Error = Error$;
export type ErrorEvent = ErrorEvent$;
export type FileCitation = FileCitation$;
export type FileSearch = FileSearch$;
export type FileSearchCall = FileSearchCall$;
export type FileSearchCallStep = FileSearchCallStep$;
export type FileSearchResult = FileSearchResult$;
export type FileSearchResultStep = FileSearchResultStep$;
export type FindRequest = FindRequest$;
export type FixRequest = FixRequest$;
export type Function = Function$;
export type FunctionCallStep = FunctionCallStep$;
export type FunctionResult = FunctionResult$;
export type FunctionResultStep = FunctionResultStep$;
export type GenerationConfig = GenerationConfig$;
export type GetEnvironmentFilesResponse = GetEnvironmentFilesResponse$;
export type GoogleMaps = GoogleMaps$;
export type GoogleMapsCall = GoogleMapsCall$;
export type GoogleMapsCallArguments = GoogleMapsCallArguments$;
export type GoogleMapsCallStep = GoogleMapsCallStep$;
export type GoogleMapsResult = GoogleMapsResult$;
export type GoogleMapsResultStep = GoogleMapsResultStep$;
export type GoogleSearch = GoogleSearch$;
export type GoogleSearchCall = GoogleSearchCall$;
export type GoogleSearchCallArguments = GoogleSearchCallArguments$;
export type GoogleSearchCallStep = GoogleSearchCallStep$;
export type GoogleSearchResult = GoogleSearchResult$;
export type GoogleSearchResultStep = GoogleSearchResultStep$;
export type GroundingToolCount = GroundingToolCount$;
export type HarmCategory = HarmCategory$;
export type Image = Image$;
export type ImageConfig = ImageConfig$;
export type ImageContent = ImageContent$;
export type ImageResponseFormat = ImageResponseFormat$;
export type InputTokensByModality = InputTokensByModality$;
export type Interaction = Interaction$;
export type InteractionCancelParams = InteractionCancelParams$;
export type InteractionCompletedEvent = InteractionCompletedEvent$;
export type InteractionCreatedEvent = InteractionCreatedEvent$;
export type InteractionCreateParams = InteractionCreateParams$;
export type InteractionDeleteParams = InteractionDeleteParams$;
export type InteractionDeleteResponse = InteractionDeleteResponse$;
export type InteractionGetParams = InteractionGetParams$;
export type InteractionGetParamsNonStreaming =
  InteractionGetParamsNonStreaming$;
export type InteractionGetParamsStreaming = InteractionGetParamsStreaming$;
export type InteractionSSEEvent = InteractionSSEEvent$;
export type InteractionStatusUpdate = InteractionStatusUpdate$;
export type ListTriggerExecutionsResponse = ListTriggerExecutionsResponse$;
export type ListTriggersResponse = ListTriggersResponse$;
export type MCPServer = MCPServer$;
export type MCPServerToolCall = MCPServerToolCall$;
export type MCPServerToolCallStep = MCPServerToolCallStep$;
export type MCPServerToolResult = MCPServerToolResult$;
export type MCPServerToolResultStep = MCPServerToolResultStep$;
export type Metadata = Metadata$;
export type Model = Model$;
export type ModelOutputStep = ModelOutputStep$;
export type OutputTokensByModality = OutputTokensByModality$;
export type PingWebhookRequest = PingWebhookRequest$;
export type Place = Place$;
export type PlaceCitation = PlaceCitation$;
export type ProcessingCall = ProcessingCall$;
export type ProcessingCallStep = ProcessingCallStep$;
export type ProcessingResult = ProcessingResult$;
export type ProcessingResultStep = ProcessingResultStep$;
export type Result = Result$;
export type Retrieval = Retrieval$;
export type RetrievalCallArguments = RetrievalCallArguments$;
export type RetrievalCallDelta = RetrievalCallDelta$;
export type RetrievalCallStep = RetrievalCallStep$;
export type RetrievalResultDelta = RetrievalResultDelta$;
export type RetrievalResultStep = RetrievalResultStep$;
export type ReviewSnippet = ReviewSnippet$;
export type RotateSigningSecretRequest = RotateSigningSecretRequest$;
export type SafetySetting = SafetySetting$;
export type SessionConfig = SessionConfig$;
export type SigningSecret = SigningSecret$;
export type Smart = Smart$;
export type Source = Source$;
export type SourceFile = SourceFile$;
export type SpeechConfig = SpeechConfig$;
export type Static = Static$;
export type Step = Step$;
export type StepDelta = StepDelta$;
export type StepStart = StepStart$;
export type StepStop = StepStop$;
export type Text = Text$;
export type TextAnnotationDelta = TextAnnotationDelta$;
export type TextContent = TextContent$;
export type TextResponseFormat = TextResponseFormat$;
export type ThinkingLevel = ThinkingLevel$;
export type ThoughtSignature = ThoughtSignature$;
export type ThoughtStep = ThoughtStep$;
export type ThoughtSummary = ThoughtSummary$;
export type Tool = Tool$;
export type ToolChoiceConfig = ToolChoiceConfig$;
export type ToolChoiceType = ToolChoiceType$;
export type ToolUseTokensByModality = ToolUseTokensByModality$;
export type TranscriptionConfig = TranscriptionConfig$;
export type TranscriptionMode = TranscriptionMode$;
export type Trigger = Trigger$;
export type TriggerCreateParams = TriggerCreateParams$;
export type TriggerDeleteParams = TriggerDeleteParams$;
export type TriggerDeleteResponse = TriggerDeleteResponse$;
export type TriggerExecution = TriggerExecution$;
export type TriggerGetParams = TriggerGetParams$;
export type TriggerListExecutionsParams = TriggerListExecutionsParams$;
export type TriggerListExecutionsResponse = TriggerListExecutionsResponse$;
export type TriggerListParams = TriggerListParams$;
export type TriggerListResponse = TriggerListResponse$;
export type TriggerRunParams = TriggerRunParams$;
export type TriggerUpdate = TriggerUpdate$;
export type TriggerUpdateParams = TriggerUpdateParams$;
export type URLCitation = URLCitation$;
export type URLContext = URLContext$;
export type URLContextCall = URLContextCall$;
export type URLContextCallArguments = URLContextCallArguments$;
export type URLContextCallStep = URLContextCallStep$;
export type URLContextResult = URLContextResult$;
export type URLContextResultStep = URLContextResultStep$;
export type Usage = Usage$;
export type UserInputStep = UserInputStep$;
export type Verbatim = Verbatim$;
export type VertexAISearchConfig = VertexAISearchConfig$;
export type Video = Video$;
export type VideoConfig = VideoConfig$;
export type VideoContent = VideoContent$;
export type VideoResponseFormat = VideoResponseFormat$;
export type Webhook = Webhook$;
export type WebhookConfig = WebhookConfig$;
export type WebhookCreateParams = WebhookCreateParams$;
export type WebhookDeleteParams = WebhookDeleteParams$;
export type WebhookDeleteResponse = WebhookDeleteResponse$;
export type WebhookGetParams = WebhookGetParams$;
export type WebhookInput = WebhookInput$;
export type WebhookListParams = WebhookListParams$;
export type WebhookListResponse = WebhookListResponse$;
export type WebhookPingParams = WebhookPingParams$;
export type WebhookPingResponse = WebhookPingResponse$;
export type WebhookRotateSigningSecretParams =
  WebhookRotateSigningSecretParams$;
export type WebhookRotateSigningSecretResponse =
  WebhookRotateSigningSecretResponse$;
export type WebhookUpdate = WebhookUpdate$;
export type WebhookUpdateParams = WebhookUpdateParams$;
export type WordInfo = WordInfo$;
export declare namespace Agents {
  export type Agent = Agent$;
  export type AgentCreateParams = AgentCreateParams$;
  export type AgentDeleteParams = AgentDeleteParams$;
  export type AgentDeleteResponse = AgentDeleteResponse$;
  export type AgentGetParams = AgentGetParams$;
  export type AgentListParams = AgentListParams$;
  export type AgentListResponse = AgentListResponse$;
  export type AgentTool = AgentTool$;
}
export declare namespace Environments {
  export interface CreateEnvironmentRequest extends CreateEnvironmentRequest$ {}
  export interface Environment extends Environment$ {}
  export type EnvironmentDeleteResponse = EnvironmentDeleteResponse$;
  export type EnvironmentFile = EnvironmentFile$;
  export type EnvironmentListResponse = EnvironmentListResponse$;
  export type GetEnvironmentFilesResponse = GetEnvironmentFilesResponse$;
  export namespace CreateEnvironmentRequest {
    export type Allowlist = Allowlist$;
  }
  export namespace Environment {
    export type Allowlist = Allowlist$2;
  }
}
export declare namespace Interactions {
  export type AllowedTools = AllowedTools$;
  export type Annotation = Annotation$;
  export type AntigravityAgentConfig = AntigravityAgentConfig$;
  export type AudioContent = AudioContent$;
  export type AudioResponseFormat = AudioResponseFormat$;
  export type CodeExecutionCallArguments = CodeExecutionCallArguments$;
  export interface CodeExecutionCallStep extends CodeExecutionCallStep$ {}
  export type CodeExecutionResultStep = CodeExecutionResultStep$;
  export interface CodeMenderAgentConfig extends CodeMenderAgentConfig$ {}
  export type Content = Content$;
  export type CreateAgentInteractionParamsNonStreaming =
    CreateAgentInteractionParamsNonStreaming$;
  export type CreateAgentInteractionParamsStreaming =
    CreateAgentInteractionParamsStreaming$;
  export type CreateModelInteractionParamsNonStreaming =
    CreateModelInteractionParamsNonStreaming$;
  export type CreateModelInteractionParamsStreaming =
    CreateModelInteractionParamsStreaming$;
  export type DeepResearchAgentConfig = DeepResearchAgentConfig$;
  export type DocumentContent = DocumentContent$;
  export type DynamicAgentConfig = DynamicAgentConfig$;
  export interface Environment extends Environment$2 {}
  export type Error = Error$;
  export interface ErrorEvent extends ErrorEvent$ {}
  export type FileCitation = FileCitation$;
  export type FileSearchCallStep = FileSearchCallStep$;
  export type FileSearchResultStep = FileSearchResultStep$;
  export type Function = Function$;
  export type FunctionCallStep = FunctionCallStep$;
  export type FunctionResultStep = FunctionResultStep$;
  export type GenerationConfig = GenerationConfig$;
  export type GoogleMapsCallArguments = GoogleMapsCallArguments$;
  export interface GoogleMapsCallStep extends GoogleMapsCallStep$ {}
  export interface GoogleMapsResult extends GoogleMapsResult$ {}
  export interface GoogleMapsResultStep extends GoogleMapsResultStep$ {}
  export type GoogleSearchCallArguments = GoogleSearchCallArguments$;
  export interface GoogleSearchCallStep extends GoogleSearchCallStep$ {}
  export type GoogleSearchResult = GoogleSearchResult$;
  export interface GoogleSearchResultStep extends GoogleSearchResultStep$ {}
  export type HarmCategory = HarmCategory$;
  export type ImageConfig = ImageConfig$;
  export type ImageContent = ImageContent$;
  export type ImageResponseFormat = ImageResponseFormat$;
  export type Interaction = Interaction$;
  export type InteractionCancelParams = InteractionCancelParams$;
  export type InteractionCompletedEvent = InteractionCompletedEvent$;
  export type InteractionCreatedEvent = InteractionCreatedEvent$;
  export type InteractionCreateParams = InteractionCreateParams$;
  export type InteractionDeleteParams = InteractionDeleteParams$;
  export type InteractionDeleteResponse = InteractionDeleteResponse$;
  export type InteractionGetParams = InteractionGetParams$;
  export type InteractionGetParamsNonStreaming =
    InteractionGetParamsNonStreaming$;
  export type InteractionGetParamsStreaming = InteractionGetParamsStreaming$;
  export type InteractionSSEEvent = InteractionSSEEvent$;
  export type InteractionStatusUpdate = InteractionStatusUpdate$;
  export type MCPServerToolCallStep = MCPServerToolCallStep$;
  export type MCPServerToolResultStep = MCPServerToolResultStep$;
  export type Model = Model$;
  export type ModelOutputStep = ModelOutputStep$;
  export interface PlaceCitation extends PlaceCitation$ {}
  export type ProcessingCallStep = ProcessingCallStep$;
  export type ProcessingResultStep = ProcessingResultStep$;
  export type RetrievalCallArguments = RetrievalCallArguments$;
  export interface RetrievalCallDelta extends RetrievalCallDelta$ {}
  export interface RetrievalCallStep extends RetrievalCallStep$ {}
  export type RetrievalResultDelta = RetrievalResultDelta$;
  export type RetrievalResultStep = RetrievalResultStep$;
  export type SafetySetting = SafetySetting$;
  export type SpeechConfig = SpeechConfig$;
  export type Step = Step$;
  export interface StepDelta extends StepDelta$ {}
  export type StepStart = StepStart$;
  export type StepStop = StepStop$;
  export type TextContent = TextContent$;
  export type TextResponseFormat = TextResponseFormat$;
  export type ThinkingLevel = ThinkingLevel$;
  export type ThoughtStep = ThoughtStep$;
  export type Tool = Tool$;
  export type ToolChoiceConfig = ToolChoiceConfig$;
  export type ToolChoiceType = ToolChoiceType$;
  export type TranscriptionConfig = TranscriptionConfig$;
  export type TranscriptionMode = TranscriptionMode$;
  export type URLCitation = URLCitation$;
  export type URLContextCallArguments = URLContextCallArguments$;
  export interface URLContextCallStep extends URLContextCallStep$ {}
  export type URLContextResult = URLContextResult$;
  export interface URLContextResultStep extends URLContextResultStep$ {}
  export interface Usage extends Usage$ {}
  export type UserInputStep = UserInputStep$;
  export type VideoConfig = VideoConfig$;
  export interface VideoContent extends VideoContent$ {}
  export type VideoResponseFormat = VideoResponseFormat$;
  export type WebhookConfig = WebhookConfig$;
  export type WordInfo = WordInfo$;
  export namespace CodeExecutionCallStep {
    export type Arguments = Arguments$;
  }
  export namespace CodeMenderAgentConfig {
    export interface FindRequest extends FindRequest$ {}
    export interface FixRequest extends FixRequest$ {}
    export type SessionConfig = SessionConfig$;
    export namespace FindRequest {
      export type SourceFile = SourceFile$;
    }
    export namespace FixRequest {
      export type SourceFile = SourceFile$2;
    }
  }
  export namespace Environment {
    export type Allowlist = Allowlist$3;
    export type Source = Source$;
  }
  export namespace ErrorEvent {
    export type Error = Error$2;
  }
  export namespace GoogleMapsCallStep {
    export type Arguments = Arguments$2;
  }
  export namespace GoogleMapsResult {
    export interface Place extends Place$ {}
    export namespace Place {
      export type ReviewSnippet = ReviewSnippet$;
    }
  }
  export namespace GoogleMapsResultStep {
    export interface Result extends Result$ {}
    export namespace Result {
      export interface Place extends Place$2 {}
      export namespace Place {
        export type ReviewSnippet = ReviewSnippet$2;
      }
    }
  }
  export namespace GoogleSearchCallStep {
    export type Arguments = Arguments$3;
  }
  export namespace GoogleSearchResultStep {
    export type Result = Result$2;
  }
  export namespace InteractionGetParams {
    export type InteractionGetParamsNonStreaming =
      InteractionGetParamsNonStreaming$2;
    export type InteractionGetParamsStreaming = InteractionGetParamsStreaming$2;
  }
  export namespace PlaceCitation {
    export type ReviewSnippet = ReviewSnippet$3;
  }
  export namespace RetrievalCallDelta {
    export type Arguments = Arguments$4;
  }
  export namespace RetrievalCallStep {
    export type Arguments = Arguments$5;
  }
  export namespace StepDelta {
    export type ArgumentsDelta = ArgumentsDelta$;
    export type Audio = Audio$;
    export type CodeExecutionCall = CodeExecutionCall$;
    export type CodeExecutionResult = CodeExecutionResult$;
    export type Document = Document$;
    export type FileSearchCall = FileSearchCall$;
    export type FileSearchResult = FileSearchResult$;
    export type FunctionResult = FunctionResult$;
    export type GoogleMapsCall = GoogleMapsCall$;
    export type GoogleMapsResult = GoogleMapsResult$2;
    export type GoogleSearchCall = GoogleSearchCall$;
    export type GoogleSearchResult = GoogleSearchResult$2;
    export type Image = Image$;
    export type MCPServerToolCall = MCPServerToolCall$;
    export type MCPServerToolResult = MCPServerToolResult$;
    export type Metadata = Metadata$;
    export type ProcessingCall = ProcessingCall$;
    export type ProcessingResult = ProcessingResult$;
    export type Text = Text$;
    export type TextAnnotationDelta = TextAnnotationDelta$;
    export type ThoughtSignature = ThoughtSignature$;
    export type ThoughtSummary = ThoughtSummary$;
    export type URLContextCall = URLContextCall$;
    export type URLContextResult = URLContextResult$2;
    export type Video = Video$;
  }
  export namespace Tool {
    export type CodeExecution = CodeExecution$;
    export type ComputerUse = ComputerUse$;
    export type FileSearch = FileSearch$;
    export type GoogleMaps = GoogleMaps$;
    export type GoogleSearch = GoogleSearch$;
    export type MCPServer = MCPServer$;
    export interface Retrieval extends Retrieval$ {}
    export type URLContext = URLContext$;
    export namespace Retrieval {
      export type VertexAISearchConfig = VertexAISearchConfig$;
    }
  }
  export namespace TranscriptionMode {
    export type Smart = Smart$;
    export type Verbatim = Verbatim$;
  }
  export namespace URLContextCallStep {
    export type Arguments = Arguments$6;
  }
  export namespace URLContextResultStep {
    export type Result = Result$3;
  }
  export namespace Usage {
    export type CachedTokensByModality = CachedTokensByModality$;
    export type GroundingToolCount = GroundingToolCount$;
    export type InputTokensByModality = InputTokensByModality$;
    export type OutputTokensByModality = OutputTokensByModality$;
    export type ToolUseTokensByModality = ToolUseTokensByModality$;
  }
  export namespace VideoContent {
    export type Static = Static$;
  }
}
export declare namespace Triggers {
  export type ListTriggerExecutionsResponse = ListTriggerExecutionsResponse$;
  export type ListTriggersResponse = ListTriggersResponse$;
  export type Trigger = Trigger$;
  export type TriggerCreateParams = TriggerCreateParams$;
  export type TriggerDeleteParams = TriggerDeleteParams$;
  export type TriggerDeleteResponse = TriggerDeleteResponse$;
  export type TriggerExecution = TriggerExecution$;
  export type TriggerGetParams = TriggerGetParams$;
  export type TriggerListExecutionsParams = TriggerListExecutionsParams$;
  export type TriggerListExecutionsResponse = TriggerListExecutionsResponse$;
  export type TriggerListParams = TriggerListParams$;
  export type TriggerListResponse = TriggerListResponse$;
  export type TriggerRunParams = TriggerRunParams$;
  export type TriggerUpdate = TriggerUpdate$;
  export type TriggerUpdateParams = TriggerUpdateParams$;
}
export declare namespace Webhooks {
  export type PingWebhookRequest = PingWebhookRequest$;
  export type RotateSigningSecretRequest = RotateSigningSecretRequest$;
  export type SigningSecret = SigningSecret$;
  export type Webhook = Webhook$;
  export type WebhookCreateParams = WebhookCreateParams$;
  export type WebhookDeleteParams = WebhookDeleteParams$;
  export type WebhookDeleteResponse = WebhookDeleteResponse$;
  export type WebhookGetParams = WebhookGetParams$;
  export type WebhookInput = WebhookInput$;
  export type WebhookListParams = WebhookListParams$;
  export type WebhookListResponse = WebhookListResponse$;
  export type WebhookPingParams = WebhookPingParams$;
  export type WebhookPingResponse = WebhookPingResponse$;
  export type WebhookRotateSigningSecretParams =
    WebhookRotateSigningSecretParams$;
  export type WebhookRotateSigningSecretResponse =
    WebhookRotateSigningSecretResponse$;
  export type WebhookUpdate = WebhookUpdate$;
  export type WebhookUpdateParams = WebhookUpdateParams$;
}
