/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsFilesList } from "../funcs/environments-files-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as environments from "../models/environments/index.js";
import { GetEnvironmentFilesParams } from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Files extends ClientSDK {
  /**
   * Retrieves file metadata or directory contents from an environment's snapshot. To download file contents directly, pass ?alt=media or use the files.download helper.
   */
  list(
    environment: string,
    path: string,
    params?: GetEnvironmentFilesParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<environments.GetEnvironmentFilesResponse> {
    return unwrapAsAPIPromise(environmentsFilesList(
      this,
      environment,
      path,
      params?.api_version,
      params?.page_size,
      params?.page_token,
      params?.recursive,
      options,
    ));
  }
}
