/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type CancelInteractionByIdGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type CancelInteractionByIdRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * The unique identifier of the interaction to cancel.
   */
  id: string;
};
