/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as triggers from "../triggers/index.js";

export type CreateTriggerGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type CreateTriggerRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  body: triggers.TriggerCreateParams;
};
