/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Stream } from "../../lib/event-streams.js";
import * as interactions from "../interactions/index.js";

export type CreateInteractionGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

/**
 * The request body.
 */
export type CreateInteractionRequestBody =
  | interactions.CreateAgentInteraction
  | interactions.CreateModelInteraction;

export type CreateInteractionRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * The request body.
   */
  body:
    | interactions.CreateAgentInteraction
    | interactions.CreateModelInteraction;
};

export type CreateInteractionResponse =
  | interactions.Interaction
  | Stream<interactions.InteractionSSEEvent>;
