/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as agents from "../agents/index.js";

export type CreateAgentGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type CreateAgentRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * The request body.
   */
  body: agents.Agent;
};
