/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as webhooks from "../webhooks/index.js";

export type CreateWebhookGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type CreateWebhookRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Required. The webhook to create.
   */
  body: webhooks.WebhookInput;
};
