/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DeleteWebhookGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type DeleteWebhookRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Required. The ID of the webhook to delete.
   *
   * @remarks
   * Format: `{webhook_id}`
   */
  id: string;
};
