/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DeleteEnvironmentGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type DeleteEnvironmentRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
   */
  id: string;
};
