/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DeleteAgentGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type DeleteAgentRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  id: string;
};
