/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DeleteInteractionGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type DeleteInteractionRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * The unique identifier of the interaction to delete.
   */
  id: string;
};
