/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DeleteTriggerGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type DeleteTriggerRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Resource name of the trigger.
   */
  id: string;
};
