/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Stream } from "../../lib/event-streams.js";
import * as interactions from "../interactions/index.js";

export type GetInteractionByIdGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type GetInteractionByIdRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * The unique identifier of the interaction to retrieve.
   */
  id: string;
  /**
   * If set to true, includes the input in the response.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  include_input?: boolean | undefined;
  /**
   * Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.
   */
  last_event_id?: string | undefined;
  /**
   * If set to true, the generated content will be streamed incrementally.
   */
  stream?: boolean | undefined;
};

export type GetInteractionByIdResponse =
  | interactions.Interaction
  | Stream<interactions.InteractionSSEEvent>;
