/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type GetWebhookGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type GetWebhookRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Required. The ID of the webhook to retrieve.
   */
  id: string;
};
