/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type GetEnvironmentFilesGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type GetEnvironmentFilesRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  environment: string;
  path: string;
  /**
   * Optional. Maximum number of entries to return per page (for directory listing).
   */
  page_size?: number | undefined;
  /**
   * Optional. Pagination token for directory listing.
   */
  page_token?: string | undefined;
  /**
   * Optional. If true and the path is a directory, recursively lists all files.
   */
  recursive?: boolean | undefined;
};
