/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListWebhooksGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type ListWebhooksRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Optional. The maximum number of webhooks to return. The service may return fewer than
   *
   * @remarks
   * this value. If unspecified, at most 50 webhooks will be returned.
   * The maximum value is 1000.
   */
  page_size?: number | undefined;
  /**
   * Optional. A page token, received from a previous `ListWebhooks` call.
   *
   * @remarks
   * Provide this to retrieve the subsequent page.
   */
  page_token?: string | undefined;
};
