/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListEnvironmentsGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type ListEnvironmentsRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Optional. Maximum number of environments to return.\nIf unspecified, defaults to 50. Maximum is 1000.
   */
  page_size?: number | undefined;
  /**
   * Optional. Pagination token.
   */
  page_token?: string | undefined;
};
