/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListAgentsGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type ListAgentsRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  page_size?: number | undefined;
  page_token?: string | undefined;
  parent?: string | undefined;
};
