/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListTriggersGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type ListTriggersRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Optional. Filter expression (e.g., by state).
   */
  filter?: string | undefined;
  /**
   * Optional. The maximum number of triggers to return per page.
   */
  page_size?: number | undefined;
  /**
   * Optional. A page token from a previous ListTriggers call.
   */
  page_token?: string | undefined;
};
