/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as webhooks from "../webhooks/index.js";

export type PingWebhookGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type PingWebhookRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Required. The ID of the webhook to ping.
   *
   * @remarks
   * Format: `{webhook_id}`
   */
  id: string;
  /**
   * The request body.
   */
  body?: webhooks.PingWebhookRequest | undefined;
};
