/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type RunTriggerGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type RunTriggerRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Resource name of the trigger.
   */
  trigger_id: string;
};
