/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as webhooks from "../webhooks/index.js";

export type UpdateWebhookGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type UpdateWebhookRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Required. The ID of the webhook to update.
   */
  id: string;
  /**
   * Optional. The list of fields to update.
   */
  update_mask?: string | undefined;
  /**
   * Required. The webhook to update.
   */
  body?: webhooks.WebhookUpdate | undefined;
};
