/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { TriggerExecution } from "./trigger-execution.js";

/**
 * Response message for TriggerService.ListTriggerExecutions.
 */
export type ListTriggerExecutionsResponse = {
  /**
   * A page token, received from a previous `ListTriggerExecutions` call.
   *
   * @remarks
   * Provide this to retrieve the subsequent page.
   */
  next_page_token?: string | undefined;
  /**
   * The list of trigger executions.
   */
  trigger_executions?: Array<TriggerExecution> | undefined;
};
