/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

/**
 * Required. The interaction request template to be executed.
 */
export type Interaction =
  | interactions.CreateAgentInteraction
  | interactions.CreateModelInteraction;

/**
 * Parameters for creating a trigger.
 */
export type TriggerCreateParams = {
  /**
   * Optional. The display name of the trigger.
   */
  display_name?: string | undefined;
  /**
   * Optional. The environment ID for the trigger execution.
   */
  environment_id?: string | undefined;
  /**
   * Optional. The execution timeout for the triggered interaction.
   */
  execution_timeout_seconds?: number | undefined;
  /**
   * Required. The interaction request template to be executed.
   */
  interaction:
    | interactions.CreateAgentInteraction
    | interactions.CreateModelInteraction;
  /**
   * Optional. The maximum number of consecutive failures allowed before the trigger is automatically paused (status becomes ERROR).
   */
  max_consecutive_failures?: number | undefined;
  /**
   * Required. The cron schedule on which the trigger should run. Standard cron format.
   */
  schedule: string;
  /**
   * Required. Time zone in which the schedule should be interpreted.
   */
  time_zone: string;
};
