/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Output only. The status of the execution.
 */
export type TriggerExecutionStatus =
  | "in_progress"
  | "completed"
  | "failed"
  | "skipped"
  | "timed_out"
  | (string & {});

/**
 * An execution instance of a trigger.
 */
export type TriggerExecution = {
  /**
   * Output only. The time when the execution finished.
   */
  end_time?: string | undefined;
  /**
   * Output only. The environment ID used for the execution.
   */
  environment_id?: string | undefined;
  /**
   * Output only. The error message if the execution failed.
   */
  error?: string | undefined;
  /**
   * Required. Output only. Identifier. The ID of the trigger execution.
   */
  id: string;
  /**
   * Output only. The ID of the interaction created by this execution, if any.
   */
  interaction_id?: string | undefined;
  /**
   * Output only. The time when the execution was scheduled to run.
   */
  scheduled_time?: string | undefined;
  /**
   * Output only. The time when the execution started.
   */
  start_time?: string | undefined;
  /**
   * Output only. The status of the execution.
   */
  status?: TriggerExecutionStatus | undefined;
  /**
   * Required. Output only. Identifier. The ID of the trigger that created this execution.
   */
  trigger_id: string;
};
