/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Optional. The status of the trigger.
 */
export type TriggerUpdateStatus = "active" | "paused" | "error";

/**
 * Represents the fields of a Trigger that can be updated.
 */
export type TriggerUpdate = {
  /**
   * Optional. The display name of the trigger.
   */
  display_name?: string | undefined;
  /**
   * Optional. The status of the trigger.
   */
  status?: TriggerUpdateStatus | undefined;
};
