/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

/**
 * Output only. The current status of the trigger.
 */
export type TriggerStatus = "active" | "paused" | "error" | (string & {});

/**
 * A trigger configuration that is scheduled to run an agent.
 */
export type Trigger = {
  /**
   * Output only. The number of consecutive failures that have occurred
   *
   * @remarks
   * since the last successful execution.
   */
  consecutive_failure_count?: number | undefined;
  /**
   * Output only. The time when the trigger was created.
   */
  create_time?: string | undefined;
  /**
   * Optional. The display name of the trigger.
   */
  display_name?: string | undefined;
  /**
   * Optional. The environment ID for the trigger execution.
   */
  environment_id?: string | undefined;
  /**
   * Optional. The execution timeout for the triggered interaction.
   */
  execution_timeout_seconds?: number | undefined;
  /**
   * Required. Output only. Identifier. The ID of the trigger.
   */
  id: string;
  /**
   * The Interaction resource.
   */
  interaction: interactions.Interaction;
  /**
   * Output only. The time when the trigger was last paused.
   */
  last_pause_time?: string | undefined;
  /**
   * Output only. The time when the trigger was last resumed.
   */
  last_resume_time?: string | undefined;
  /**
   * Output only. The time when the trigger was last run.
   */
  last_run_time?: string | undefined;
  /**
   * Optional. The maximum number of consecutive failures allowed before
   *
   * @remarks
   * the trigger is automatically paused (status becomes ERROR).
   */
  max_consecutive_failures?: number | undefined;
  /**
   * Output only. The time when the trigger is scheduled to run next.
   */
  next_run_time?: string | undefined;
  /**
   * Output only. The ID of the last interaction created by this trigger.
   */
  previous_interaction_id?: string | undefined;
  /**
   * Required. The cron schedule on which the trigger should run.
   *
   * @remarks
   * Standard cron format.
   */
  schedule: string;
  /**
   * Output only. The current status of the trigger.
   */
  status?: TriggerStatus | undefined;
  /**
   * Required. Time zone in which the schedule should be interpreted.
   */
  time_zone: string;
  /**
   * Output only. The time when the trigger was last updated.
   */
  update_time?: string | undefined;
};
