/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The agent to interact with.
 */
export type AgentOption =
  | "deep-research-pro-preview-12-2025"
  | "deep-research-preview-04-2026"
  | "deep-research-max-preview-04-2026"
  | "antigravity-preview-05-2026"
  | (string & {});
