/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ToolChoiceType } from "./tool-choice-type.js";

/**
 * The configuration for allowed tools.
 */
export type AllowedTools = {
  mode?: ToolChoiceType | undefined;
  /**
   * The names of the allowed tools.
   */
  tools?: Array<string> | undefined;
};
