/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for the Antigravity agent runtime.
 *
 * @remarks
 * Provides server-side control over the agent's execution environment
 * and tool configuration.
 */
export type AntigravityAgentConfig = {
  /**
   * Max total tokens for the agent run.
   */
  max_total_tokens?: string | undefined;
  /**
   * The model to use for agent reasoning.
   */
  model?: string | undefined;
  type: "antigravity";
};
