/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type AudioDeltaMimeType =
  | "audio/wav"
  | "audio/mp3"
  | "audio/aiff"
  | "audio/aac"
  | "audio/ogg"
  | "audio/flac"
  | "audio/mpeg"
  | "audio/m4a"
  | "audio/l16"
  | "audio/opus"
  | "audio/alaw"
  | "audio/mulaw"
  | "audio/webm"
  | (string & {});

export type AudioDelta = {
  /**
   * The number of audio channels.
   */
  channels?: number | undefined;
  data?: string | undefined;
  mime_type?: AudioDeltaMimeType | undefined;
  /**
   * Deprecated. Use sample_rate instead. The value is ignored.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  rate?: number | undefined;
  /**
   * The sample rate of the audio.
   */
  sample_rate?: number | undefined;
  type: "audio";
  uri?: string | undefined;
};
