/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The mime type of the audio.
 */
export type AudioContentMimeType =
  | "audio/wav"
  | "audio/mp3"
  | "audio/aiff"
  | "audio/aac"
  | "audio/ogg"
  | "audio/flac"
  | "audio/mpeg"
  | "audio/m4a"
  | "audio/l16"
  | "audio/opus"
  | "audio/alaw"
  | "audio/mulaw"
  | "audio/webm"
  | (string & {});

/**
 * An audio content block.
 */
export type AudioContent = {
  /**
   * The number of audio channels.
   */
  channels?: number | undefined;
  /**
   * The audio content.
   */
  data?: string | undefined;
  /**
   * The mime type of the audio.
   */
  mime_type?: AudioContentMimeType | undefined;
  /**
   * The sample rate of the audio.
   */
  sample_rate?: number | undefined;
  type: "audio";
  /**
   * The URI of the audio.
   */
  uri?: string | undefined;
};
