/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The delivery mode for the audio output.
 */
export type AudioResponseFormatDelivery = "inline" | "uri" | (string & {});

/**
 * The MIME type of the audio output.
 */
export type AudioResponseFormatMimeType =
  | "audio/mp3"
  | "audio/ogg_opus"
  | "audio/l16"
  | "audio/wav"
  | "audio/alaw"
  | "audio/mulaw"
  | (string & {});

/**
 * Configuration for audio output format.
 */
export type AudioResponseFormat = {
  /**
   * Bit rate in bits per second (bps). Only applicable for compressed formats
   *
   * @remarks
   * (MP3, Opus).
   */
  bit_rate?: number | undefined;
  /**
   * The delivery mode for the audio output.
   */
  delivery?: AudioResponseFormatDelivery | undefined;
  /**
   * The MIME type of the audio output.
   */
  mime_type?: AudioResponseFormatMimeType | undefined;
  /**
   * Sample rate in Hz.
   */
  sample_rate?: number | undefined;
  type: "audio";
};
