/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CodeExecutionCallArguments } from "./code-execution-call-arguments.js";

/**
 * Code execution call step.
 */
export type CodeExecutionCallStep = {
  /**
   * The arguments to pass to the code execution.
   */
  arguments: CodeExecutionCallArguments;
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "code_execution_call";
};
