/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A tool that can be used by the model to execute code.
 */
export type CodeExecution = {
  type: "code_execution";
};
