/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FindRequest } from "./find-request.js";
import { FixRequest } from "./fix-request.js";
import { SessionConfig } from "./session-config.js";

/**
 * Configuration for the CodeMender agent.
 */
export type CodeMenderAgentConfig = {
  /**
   * Request parameters specific to FIND sessions, used for discovering
   *
   * @remarks
   * vulnerabilities in a codebase.
   */
  find_request?: FindRequest | undefined;
  /**
   * Request parameters specific to FIX sessions, used for generating and
   *
   * @remarks
   * validating security patches.
   */
  fix_request?: FixRequest | undefined;
  /**
   * The name of the model to use for the CodeMender agent. One
   *
   * @remarks
   * CodeMender session will only use one model.
   */
  model?: string | undefined;
  /**
   * The configuration of CodeMender sessions.
   */
  session_config?: SessionConfig | undefined;
  /**
   * Parameter for grouping multiple interactions that belong to
   *
   * @remarks
   * the same CodeMender session.
   */
  session_id?: string | undefined;
  type: "code-mender";
};
