/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Programming language of the `code`.
 */
export type Language = "python";

/**
 * The arguments to pass to the code execution.
 */
export type CodeExecutionCallArguments = {
  /**
   * The code to be executed.
   */
  code?: string | undefined;
  /**
   * Programming language of the `code`.
   */
  language?: Language | undefined;
};
