/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DisabledSafetyPolicy =
  | "financial_transactions"
  | "sensitive_data_modification"
  | "communication_tool"
  | "account_creation"
  | "data_modification"
  | "user_consent_management"
  | "legal_terms_and_agreements"
  | (string & {});

/**
 * The environment being operated.
 */
export type EnvironmentEnum = "browser" | "mobile" | "desktop" | (string & {});

/**
 * A tool that can be used by the model to interact with the computer.
 */
export type ComputerUse = {
  /**
   * Optional. Disabled safety policies for computer use.
   */
  disabled_safety_policies?: Array<DisabledSafetyPolicy> | undefined;
  /**
   * Whether enable the prompt injection detection check on computer-use
   *
   * @remarks
   * request.
   */
  enable_prompt_injection_detection?: boolean | undefined;
  /**
   * The environment being operated.
   */
  environment?: EnvironmentEnum | undefined;
  /**
   * The list of predefined functions that are excluded from the model call.
   */
  excluded_predefined_functions?: Array<string> | undefined;
  type: "computer_use";
};
