/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AudioContent } from "./audio-content.js";
import { DocumentContent } from "./document-content.js";
import { ImageContent } from "./image-content.js";
import { TextContent } from "./text-content.js";
import { VideoContent } from "./video-content.js";

/**
 * The content of the response.
 */
export type Content =
  | AudioContent
  | DocumentContent
  | ImageContent
  | TextContent
  | VideoContent;
