/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AgentOption } from "./agent-option.js";
import { AntigravityAgentConfig } from "./antigravity-agent-config.js";
import { CodeMenderAgentConfig } from "./code-mender-agent-config.js";
import { DeepResearchAgentConfig } from "./deep-research-agent-config.js";
import { DynamicAgentConfig } from "./dynamic-agent-config.js";
import { Environment } from "./environment.js";
import { InteractionsInput } from "./interactions-input.js";
import { ResponseFormat } from "./response-format.js";
import { ResponseModality } from "./response-modality.js";
import { SafetySetting } from "./safety-setting.js";
import { ServiceTier } from "./service-tier.js";
import { Tool } from "./tool.js";
import { WebhookConfig } from "./webhook-config.js";

/**
 * Configuration parameters for the agent interaction.
 */
export type CreateAgentInteractionAgentConfig =
  | AntigravityAgentConfig
  | CodeMenderAgentConfig
  | DeepResearchAgentConfig
  | DynamicAgentConfig;

/**
 * The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
 */
export type CreateAgentInteractionEnvironment = Environment | string;

/**
 * Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
 */
export type CreateAgentInteractionResponseFormat =
  | ResponseFormat
  | Array<ResponseFormat>;

/**
 * Parameters for creating agent interactions
 */
export type CreateAgentInteraction = {
  /**
   * The agent to interact with.
   */
  agent: AgentOption;
  /**
   * Configuration parameters for the agent interaction.
   */
  agent_config?:
    | AntigravityAgentConfig
    | CodeMenderAgentConfig
    | DeepResearchAgentConfig
    | DynamicAgentConfig
    | undefined;
  /**
   * Input only. Whether to run the model interaction in the background.
   */
  background?: boolean | undefined;
  /**
   * The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
   */
  environment?: Environment | string | undefined;
  /**
   * The input for the interaction.
   */
  input: InteractionsInput;
  /**
   * The labels with user-defined metadata for the request.
   */
  labels?: { [k: string]: string } | undefined;
  /**
   * The ID of the previous interaction, if any.
   */
  previous_interaction_id?: string | undefined;
  /**
   * Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
   */
  response_format?: ResponseFormat | Array<ResponseFormat> | undefined;
  /**
   * The mime type of the response. This is required if response_format is set.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_mime_type?: string | undefined;
  /**
   * The requested modalities of the response (TEXT, IMAGE, AUDIO).
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_modalities?: Array<ResponseModality> | undefined;
  /**
   * Safety settings for the interaction.
   */
  safety_settings?: Array<SafetySetting> | undefined;
  service_tier?: ServiceTier | undefined;
  /**
   * Input only. Whether to store the response and request for later retrieval.
   */
  store?: boolean | undefined;
  /**
   * Input only. Whether the interaction will be streamed.
   */
  stream?: boolean | undefined;
  /**
   * System instruction for the interaction.
   */
  system_instruction?: string | undefined;
  /**
   * A list of tool declarations the model may call during interaction.
   */
  tools?: Array<Tool> | undefined;
  /**
   * Message for configuring webhook events for a request.
   */
  webhook_config?: WebhookConfig | undefined;
};
