/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ThinkingSummaries } from "./thinking-summaries.js";

/**
 * Whether to include visualizations in the response.
 */
export type Visualization = "off" | "auto" | (string & {});

/**
 * Configuration for the Deep Research agent.
 */
export type DeepResearchAgentConfig = {
  /**
   * Enables human-in-the-loop planning for the Deep Research agent. If set to
   *
   * @remarks
   * true, the Deep Research agent will provide a research plan in its response.
   * The agent will then proceed only if the user confirms the plan in the next
   * turn.
   */
  collaborative_planning?: boolean | undefined;
  /**
   * Enables bigquery tool for the Deep Research agent.
   */
  enable_bigquery_tool?: boolean | undefined;
  thinking_summaries?: ThinkingSummaries | undefined;
  type: "deep-research";
  /**
   * Whether to include visualizations in the response.
   */
  visualization?: Visualization | undefined;
};
