/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type DocumentDeltaMimeType =
  | "application/pdf"
  | "text/csv"
  | (string & {});

export type DocumentDelta = {
  data?: string | undefined;
  mime_type?: DocumentDeltaMimeType | undefined;
  type: "document";
  uri?: string | undefined;
};
