/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The mime type of the document.
 */
export type DocumentContentMimeType =
  | "application/pdf"
  | "text/csv"
  | (string & {});

/**
 * A document content block.
 */
export type DocumentContent = {
  /**
   * The document content.
   */
  data?: string | undefined;
  /**
   * The mime type of the document.
   */
  mime_type?: DocumentContentMimeType | undefined;
  type: "document";
  /**
   * The URI of the document.
   */
  uri?: string | undefined;
};
