/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for dynamic agents.
 */
export type DynamicAgentConfig = {
  type: "dynamic";
  [additionalProperties: string]: unknown;
};
