/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EnvironmentNetworkEgressAllowlist } from "./environment-network-egress-allowlist.js";
import { Source } from "./source.js";

export type NetworkEnum = "disabled";

/**
 * Network configuration for the environment.
 */
export type Network = EnvironmentNetworkEgressAllowlist | NetworkEnum;

/**
 * Configuration for a custom environment.
 */
export type Environment = {
  /**
   * Optional. The environment ID for the interaction. If specified, the request will
   *
   * @remarks
   * update the existing environment instead of creating a new one.
   */
  environment_id?: string | undefined;
  /**
   * Network configuration for the environment.
   */
  network?: EnvironmentNetworkEgressAllowlist | NetworkEnum | undefined;
  sources?: Array<Source> | undefined;
  type: "remote";
};
