/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ErrorT } from "./error.js";

export type ErrorEvent = {
  /**
   * Error message from an interaction.
   */
  error?: ErrorT | undefined;
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "error";
};
