/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Error message from an interaction.
 */
export type ErrorT = {
  /**
   * A URI that identifies the error type.
   */
  code?: string | undefined;
  /**
   * A human-readable error message.
   */
  message?: string | undefined;
};
