/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Used to specify configuration for ExaAISearch.
 */
export type ExaAISearchConfig = {
  /**
   * Required. The API key for ExaAiSearch.
   */
  api_key: string;
  /**
   * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
   */
  custom_config?: { [k: string]: any } | undefined;
};
