/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A tool that can be used by the model to search files.
 */
export type FileSearch = {
  /**
   * The file search store names to search.
   */
  file_search_store_names?: Array<string> | undefined;
  /**
   * Metadata filter to apply to the semantic retrieval documents and chunks.
   */
  metadata_filter?: string | undefined;
  /**
   * The number of semantic retrieval chunks to retrieve.
   */
  top_k?: number | undefined;
  type: "file_search";
};
