/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A file citation annotation.
 */
export type FileCitation = {
  /**
   * User provided metadata about the retrieved context.
   */
  custom_metadata?: { [k: string]: any } | undefined;
  /**
   * The URI of the file.
   */
  document_uri?: string | undefined;
  /**
   * End of the attributed segment, exclusive.
   */
  end_index?: number | undefined;
  /**
   * The name of the file.
   */
  file_name?: string | undefined;
  /**
   * Media ID in-case of image citations, if applicable.
   */
  media_id?: string | undefined;
  /**
   * Page number of the cited document, if applicable.
   */
  page_number?: number | undefined;
  /**
   * Source attributed for a portion of the text.
   */
  source?: string | undefined;
  /**
   * Start of segment of the response that is attributed to this source.
   *
   * @remarks
   *
   * Index indicates the start of the segment, measured in bytes.
   */
  start_index?: number | undefined;
  type: "file_citation";
};
