/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type FileSearchCallDelta = {
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "file_search_call";
};
