/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Content of a single file in the codebase.
 */
export type FileContent = {
  /**
   * The UTF-8 encoded text content of the file.
   */
  content?: string | undefined;
  /**
   * The relative path of the file from the project root.
   */
  path?: string | undefined;
};
