/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Config for filters.
 */
export type Filter = {
  /**
   * Optional. String for metadata filtering.
   */
  metadata_filter?: string | undefined;
  /**
   * Optional. Only returns contexts with vector distance smaller than the
   *
   * @remarks
   * threshold.
   */
  vector_distance_threshold?: number | undefined;
  /**
   * Optional. Only returns contexts with vector similarity larger than the
   *
   * @remarks
   * threshold.
   */
  vector_similarity_threshold?: number | undefined;
};
