/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FileContent } from "./file-content.js";

/**
 * The mode of the find session.
 */
export type Mode = "scan" | "verify" | (string & {});

/**
 * Request parameters specific to FIND sessions, used for discovering
 *
 * @remarks
 * vulnerabilities in a codebase.
 */
export type FindRequest = {
  /**
   * Additional context or custom instructions provided by the user to guide
   *
   * @remarks
   * the vulnerability analysis.
   */
  description?: string | undefined;
  /**
   * The identifier of a specific finding to verify. This is primarily used in
   *
   * @remarks
   * VERIFY mode to focus the agent's execution-based validation on a single
   * vulnerability.
   */
  finding_id?: string | undefined;
  /**
   * The mode of the find session.
   */
  mode?: Mode | undefined;
  /**
   * A list of source files to provide as context for the scan.
   */
  source_files?: Array<FileContent> | undefined;
};
