/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FileContent } from "./file-content.js";

/**
 * Request parameters specific to FIX sessions, used for generating and
 *
 * @remarks
 * validating security patches.
 */
export type FixRequest = {
  /**
   * Additional context or custom instructions provided by the user to guide
   *
   * @remarks
   * the patch generation process.
   */
  description?: string | undefined;
  /**
   * The identifier of the specific security finding to be remediated. This ID
   *
   * @remarks
   * maps to a previously discovered vulnerability.
   */
  finding_id?: string | undefined;
  /**
   * A list of source files providing context for the remediation. These files
   *
   * @remarks
   * are typically the ones containing the identified vulnerability.
   */
  source_files?: Array<FileContent> | undefined;
};
