/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A function tool call step.
 */
export type FunctionCallStep = {
  /**
   * Required. The arguments to pass to the function.
   */
  arguments: { [k: string]: any };
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * Required. The name of the tool to call.
   */
  name: string;
  type: "function_call";
};
