/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A tool that can be used by the model.
 */
export type FunctionT = {
  /**
   * A description of the function.
   */
  description?: string | undefined;
  /**
   * The name of the function.
   */
  name?: string | undefined;
  /**
   * The JSON Schema for the function's parameters.
   */
  parameters?: any | undefined;
  type: "function";
};
