/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ImageConfig } from "./image-config.js";
import { SpeakerConfig } from "./speaker-config.js";
import { SpeechConfig } from "./speech-config.js";
import { ThinkingLevel } from "./thinking-level.js";
import { ThinkingSummaries } from "./thinking-summaries.js";
import { ToolChoiceConfig } from "./tool-choice-config.js";
import { ToolChoiceType } from "./tool-choice-type.js";
import { TranscriptionConfig } from "./transcription-config.js";
import { VideoConfig } from "./video-config.js";

/**
 * Optional. Speech and multi-speaker configuration.
 */
export type SpeechConfigUnion = SpeakerConfig | Array<SpeechConfig>;

/**
 * The tool choice configuration.
 */
export type ToolChoice = ToolChoiceConfig | ToolChoiceType;

/**
 * Configuration parameters for model interactions.
 */
export type GenerationConfig = {
  /**
   * The configuration for image interaction.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  image_config?: ImageConfig | undefined;
  /**
   * The maximum number of tokens to include in the response.
   */
  max_output_tokens?: number | undefined;
  /**
   * Seed used in decoding for reproducibility.
   */
  seed?: number | undefined;
  /**
   * Optional. Speech and multi-speaker configuration.
   */
  speech_config?: SpeakerConfig | Array<SpeechConfig> | undefined;
  /**
   * A list of character sequences that will stop output interaction.
   */
  stop_sequences?: Array<string> | undefined;
  thinking_level?: ThinkingLevel | undefined;
  thinking_summaries?: ThinkingSummaries | undefined;
  /**
   * The tool choice configuration.
   */
  tool_choice?: ToolChoiceConfig | ToolChoiceType | undefined;
  /**
   * Configuration for speech recognition (transcription).
   */
  transcription_config?: TranscriptionConfig | undefined;
  /**
   * Configuration options for video generation.
   */
  video_config?: VideoConfig | undefined;
};
