/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GoogleSearchCallArguments } from "./google-search-call-arguments.js";

export type GoogleSearchCallDelta = {
  /**
   * The arguments to pass to Google Search.
   */
  arguments: GoogleSearchCallArguments;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "google_search_call";
};
