/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GoogleMapsCallArguments } from "./google-maps-call-arguments.js";

/**
 * Google Maps call step.
 */
export type GoogleMapsCallStep = {
  /**
   * The arguments to pass to the Google Maps tool.
   */
  arguments?: GoogleMapsCallArguments | undefined;
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "google_maps_call";
};
