/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type GoogleSearchSearchType =
  | "web_search"
  | "image_search"
  | "enterprise_web_search"
  | (string & {});

/**
 * A tool that can be used by the model to search Google.
 */
export type GoogleSearch = {
  /**
   * The types of search grounding to enable.
   */
  search_types?: Array<GoogleSearchSearchType> | undefined;
  type: "google_search";
};
