/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GoogleSearchCallArguments } from "./google-search-call-arguments.js";

/**
 * The type of search grounding enabled.
 */
export type GoogleSearchCallStepSearchType =
  | "web_search"
  | "image_search"
  | "enterprise_web_search"
  | (string & {});

/**
 * Google Search call step.
 */
export type GoogleSearchCallStep = {
  /**
   * The arguments to pass to Google Search.
   */
  arguments: GoogleSearchCallArguments;
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * The type of search grounding enabled.
   */
  search_type?: GoogleSearchCallStepSearchType | undefined;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "google_search_call";
};
