/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The arguments to pass to Google Search.
 */
export type GoogleSearchCallArguments = {
  /**
   * Web search queries for the following-up web search.
   */
  queries?: Array<string> | undefined;
};
