/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The arguments to pass to the Google Maps tool.
 */
export type GoogleMapsCallArguments = {
  /**
   * The queries to be executed.
   */
  queries?: Array<string> | undefined;
};
