/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A tool that can be used by the model to call Google Maps.
 */
export type GoogleMaps = {
  /**
   * Whether to return a widget context token in the tool call result of the
   *
   * @remarks
   * response.
   */
  enable_widget?: boolean | undefined;
  /**
   * The latitude of the user's location.
   */
  latitude?: number | undefined;
  /**
   * The longitude of the user's location.
   */
  longitude?: number | undefined;
  type: "google_maps";
};
