/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GoogleMapsCallArguments } from "./google-maps-call-arguments.js";

export type GoogleMapsCallDelta = {
  /**
   * The arguments to pass to the Google Maps tool.
   */
  arguments?: GoogleMapsCallArguments | undefined;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "google_maps_call";
};
