/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The grounding tool type associated with the count.
 */
export type GroundingToolCountType =
  | "google_search"
  | "google_maps"
  | "retrieval"
  | (string & {});

/**
 * The number of grounding tool counts.
 */
export type GroundingToolCount = {
  /**
   * The number of grounding tool counts.
   */
  count?: number | undefined;
  /**
   * The grounding tool type associated with the count.
   */
  type?: GroundingToolCountType | undefined;
};
