/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Config for Hybrid Search.
 */
export type HybridSearch = {
  /**
   * Optional. Alpha value controls the weight between dense and sparse vector search
   *
   * @remarks
   * results.
   */
  alpha?: number | undefined;
};
