/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { MediaResolution } from "./media-resolution.js";

/**
 * The mime type of the image.
 */
export type ImageContentMimeType =
  | "image/png"
  | "image/jpeg"
  | "image/webp"
  | "image/heic"
  | "image/heif"
  | "image/gif"
  | "image/bmp"
  | "image/tiff"
  | (string & {});

/**
 * An image content block.
 */
export type ImageContent = {
  /**
   * The image content.
   */
  data?: string | undefined;
  /**
   * The mime type of the image.
   */
  mime_type?: ImageContentMimeType | undefined;
  resolution?: MediaResolution | undefined;
  type: "image";
  /**
   * The URI of the image.
   */
  uri?: string | undefined;
};
