/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ImageConfigAspectRatio =
  | "1:1"
  | "2:3"
  | "3:2"
  | "3:4"
  | "4:3"
  | "4:5"
  | "5:4"
  | "9:16"
  | "16:9"
  | "21:9"
  | "1:8"
  | "8:1"
  | "1:4"
  | "4:1"
  | (string & {});

export type ImageConfigImageSize = "1K" | "2K" | "4K" | "512" | (string & {});

/**
 * The configuration for image interaction.
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type ImageConfig = {
  aspect_ratio?: ImageConfigAspectRatio | undefined;
  image_size?: ImageConfigImageSize | undefined;
};
