/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The aspect ratio for the image output.
 */
export type ImageResponseFormatAspectRatio =
  | "1:1"
  | "2:3"
  | "3:2"
  | "3:4"
  | "4:3"
  | "4:5"
  | "5:4"
  | "9:16"
  | "16:9"
  | "21:9"
  | "1:8"
  | "8:1"
  | "1:4"
  | "4:1"
  | (string & {});

/**
 * The delivery mode for the image output.
 */
export type ImageResponseFormatDelivery = "inline" | "uri" | (string & {});

/**
 * The size of the image output.
 */
export type ImageResponseFormatImageSize =
  | "512"
  | "1K"
  | "2K"
  | "4K"
  | (string & {});

/**
 * The MIME type of the image output.
 */
export type ImageResponseFormatMimeType = "image/jpeg";

/**
 * Configuration for image output format.
 */
export type ImageResponseFormat = {
  /**
   * The aspect ratio for the image output.
   */
  aspect_ratio?: ImageResponseFormatAspectRatio | undefined;
  /**
   * The delivery mode for the image output.
   */
  delivery?: ImageResponseFormatDelivery | undefined;
  /**
   * The size of the image output.
   */
  image_size?: ImageResponseFormatImageSize | undefined;
  /**
   * The MIME type of the image output.
   */
  mime_type?: ImageResponseFormatMimeType | undefined;
  type: "image";
};
