/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { MediaResolution } from "./media-resolution.js";

export type ImageDeltaMimeType =
  | "image/png"
  | "image/jpeg"
  | "image/webp"
  | "image/heic"
  | "image/heif"
  | "image/gif"
  | "image/bmp"
  | "image/tiff"
  | (string & {});

export type ImageDelta = {
  data?: string | undefined;
  mime_type?: ImageDeltaMimeType | undefined;
  resolution?: MediaResolution | undefined;
  type: "image";
  uri?: string | undefined;
};
