/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ErrorEvent } from "./error-event.js";
import { InteractionCompletedEvent } from "./interaction-completed-event.js";
import { InteractionCreatedEvent } from "./interaction-created-event.js";
import { InteractionStatusUpdate } from "./interaction-status-update.js";
import { StepDelta } from "./step-delta.js";
import { StepStart } from "./step-start.js";
import { StepStop } from "./step-stop.js";

export type InteractionSSEEvent =
  | InteractionCreatedEvent
  | ErrorEvent
  | InteractionCompletedEvent
  | InteractionStatusUpdate
  | StepDelta
  | StepStart
  | StepStop;
