/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InteractionSseEventInteraction } from "./interaction-sse-event-interaction.js";

export type InteractionCreatedEvent = {
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "interaction.created";
  /**
   * Partial interaction resource emitted by interaction lifecycle SSE events.
   *
   * @remarks
   * Streaming lifecycle payloads may omit fields that are only available on
   * full non-streaming Interaction responses.
   */
  interaction: InteractionSseEventInteraction;
};
