/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type InteractionStatusUpdateStatus =
  | "in_progress"
  | "requires_action"
  | "completed"
  | "failed"
  | "cancelled"
  | "incomplete"
  | "budget_exceeded"
  | "queued"
  | (string & {});

export type InteractionStatusUpdate = {
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "interaction.status_update";
  interaction_id: string;
  status: InteractionStatusUpdateStatus;
};
