/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Content } from "./content.js";
import { Step } from "./step.js";

/**
 * The input for the interaction.
 */
export type InteractionsInput = Content | Array<Step> | Array<Content> | string;
