/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InteractionSSEEvent } from "./interaction-sse-event.js";

export type InteractionSSEStreamEvent = {
  data: InteractionSSEEvent;
};
