/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AgentOption } from "./agent-option.js";
import { AntigravityAgentConfig } from "./antigravity-agent-config.js";
import { AudioContent } from "./audio-content.js";
import { CodeMenderAgentConfig } from "./code-mender-agent-config.js";
import { DeepResearchAgentConfig } from "./deep-research-agent-config.js";
import { DynamicAgentConfig } from "./dynamic-agent-config.js";
import { Environment } from "./environment.js";
import { ErrorT } from "./error.js";
import { GenerationConfig } from "./generation-config.js";
import { ImageContent } from "./image-content.js";
import { InteractionsInput } from "./interactions-input.js";
import { Model } from "./model.js";
import { ResponseFormat } from "./response-format.js";
import { ResponseModality } from "./response-modality.js";
import { SafetySetting } from "./safety-setting.js";
import { ServiceTier } from "./service-tier.js";
import { Step } from "./step.js";
import { Tool } from "./tool.js";
import { Usage } from "./usage.js";
import { VideoContent } from "./video-content.js";
import { WebhookConfig } from "./webhook-config.js";

/**
 * Configuration parameters for the agent interaction.
 */
export type InteractionAgentConfig =
  | AntigravityAgentConfig
  | CodeMenderAgentConfig
  | DeepResearchAgentConfig
  | DynamicAgentConfig;

/**
 * The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
 */
export type InteractionEnvironment = Environment | string;

/**
 * Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
 */
export type InteractionResponseFormat = ResponseFormat | Array<ResponseFormat>;

/**
 * Required. Output only. The status of the interaction.
 */
export type InteractionStatus =
  | "in_progress"
  | "requires_action"
  | "completed"
  | "failed"
  | "cancelled"
  | "incomplete"
  | "budget_exceeded"
  | "queued"
  | (string & {});

/**
 * The Interaction resource.
 */
export type Interaction = {
  /**
   * The agent to interact with.
   */
  agent?: AgentOption | undefined;
  /**
   * Configuration parameters for the agent interaction.
   */
  agent_config?:
    | AntigravityAgentConfig
    | CodeMenderAgentConfig
    | DeepResearchAgentConfig
    | DynamicAgentConfig
    | undefined;
  /**
   * Output only. The time at which the response was created in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  created?: string | undefined;
  /**
   * The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
   */
  environment?: Environment | string | undefined;
  /**
   * Output only. The environment ID for the interaction. Only populated if environment
   *
   * @remarks
   * config is set in the request.
   */
  environment_id?: string | undefined;
  /**
   * Output only. Diagnostic faults / platform errors recorded on the interaction.
   */
  errors?: Array<ErrorT> | undefined;
  /**
   * Configuration parameters for model interactions.
   */
  generation_config?: GenerationConfig | undefined;
  /**
   * Required. Output only. A unique identifier for the interaction completion.
   */
  id: string;
  /**
   * The input for the interaction.
   */
  input?: InteractionsInput | undefined;
  /**
   * The labels with user-defined metadata for the request.
   */
  labels?: { [k: string]: string } | undefined;
  /**
   * The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
   */
  model?: Model | undefined;
  /**
   * An audio content block.
   */
  output_audio?: AudioContent | undefined;
  /**
   * An image content block.
   */
  output_image?: ImageContent | undefined;
  /**
   * Concatenated text from the last model output in response to the current request.
   *
   * @remarks
   *
   * Note: this is added by the SDK.
   */
  output_text?: string | undefined;
  /**
   * A video content block.
   */
  output_video?: VideoContent | undefined;
  /**
   * The ID of the previous interaction, if any.
   */
  previous_interaction_id?: string | undefined;
  /**
   * Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
   */
  response_format?: ResponseFormat | Array<ResponseFormat> | undefined;
  /**
   * The mime type of the response. This is required if response_format is set.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_mime_type?: string | undefined;
  /**
   * The requested modalities of the response (TEXT, IMAGE, AUDIO).
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_modalities?: Array<ResponseModality> | undefined;
  /**
   * Safety settings for the interaction.
   */
  safety_settings?: Array<SafetySetting> | undefined;
  service_tier?: ServiceTier | undefined;
  /**
   * Required. Output only. The status of the interaction.
   */
  status: InteractionStatus;
  /**
   * Output only. The steps that make up the interaction, when included in the response.
   */
  steps?: Array<Step> | undefined;
  /**
   * System instruction for the interaction.
   */
  system_instruction?: string | undefined;
  /**
   * A list of tool declarations the model may call during interaction.
   */
  tools?: Array<Tool> | undefined;
  /**
   * Output only. The time at which the response was last updated in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  updated?: string | undefined;
  /**
   * Statistics on the interaction request's token usage.
   */
  usage?: Usage | undefined;
  /**
   * Message for configuring webhook events for a request.
   */
  webhook_config?: WebhookConfig | undefined;
};
