/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ServiceTier } from "./service-tier.js";
import { Step } from "./step.js";
import { Usage } from "./usage.js";

/**
 * Required. Output only. The status of the interaction.
 */
export type InteractionSseEventInteractionStatus =
  | "in_progress"
  | "requires_action"
  | "completed"
  | "failed"
  | "cancelled"
  | "incomplete"
  | (string & {});

/**
 * Partial interaction resource emitted by interaction lifecycle SSE events.
 *
 * @remarks
 * Streaming lifecycle payloads may omit fields that are only available on
 * full non-streaming Interaction responses.
 */
export type InteractionSseEventInteraction = {
  /**
   * The agent to interact with.
   */
  agent?: string | undefined;
  /**
   * Output only. The time at which the response was created in ISO 8601 format.
   */
  created?: string | undefined;
  /**
   * Required. Output only. A unique identifier for the interaction completion.
   */
  id: string;
  /**
   * The model that will complete your prompt.
   */
  model?: string | undefined;
  /**
   * Output only. The resource type.
   */
  object?: string | undefined;
  service_tier?: ServiceTier | undefined;
  /**
   * Required. Output only. The status of the interaction.
   */
  status: InteractionSseEventInteractionStatus;
  /**
   * Output only. The steps that make up the interaction, if included in this event.
   */
  steps?: Array<Step> | undefined;
  /**
   * Output only. The time at which the response was last updated in ISO 8601 format.
   */
  updated?: string | undefined;
  /**
   * Statistics on the interaction request's token usage.
   */
  usage?: Usage | undefined;
};
