/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type MCPServerToolCallDelta = {
  arguments: { [k: string]: any };
  name: string;
  server_name: string;
  type: "mcp_server_tool_call";
};
