/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * MCPServer tool call step.
 */
export type MCPServerToolCallStep = {
  /**
   * Required. The JSON object of arguments for the function.
   */
  arguments: { [k: string]: any };
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * Required. The name of the tool which was called.
   */
  name: string;
  /**
   * Required. The name of the used MCP server.
   */
  server_name: string;
  type: "mcp_server_tool_call";
};
