/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { StaticMediaProcessing } from "./static-media-processing.js";

export type MediaProcessing = StaticMediaProcessing;
