/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ResponseModality } from "./response-modality.js";

/**
 * The token count for a single response modality.
 */
export type ModalityTokens = {
  modality?: ResponseModality | undefined;
  /**
   * Number of tokens for the modality.
   */
  tokens?: number | undefined;
};
