/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Content } from "./content.js";
import { Status } from "./status.js";

/**
 * Output generated by the model.
 */
export type ModelOutputStep = {
  content?: Array<Content> | undefined;
  /**
   * The `Status` type defines a logical error model that is suitable for
   *
   * @remarks
   * different programming environments, including REST APIs and RPC APIs. It is
   * used by [gRPC](https://github.com/grpc). Each `Status` message contains
   * three pieces of data: error code, error message, and error details.
   *
   * You can find out more about this error model and how to work with it in the
   * [API Design Guide](https://cloud.google.com/apis/design/errors).
   */
  error?: Status | undefined;
  type: "model_output";
};
