/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Used to specify configuration for ParallelAISearch.
 */
export type ParallelAISearchConfig = {
  /**
   * Optional. The API key for ParallelAiSearch.
   */
  api_key?: string | undefined;
  /**
   * Optional. Custom configs for ParallelAiSearch.
   */
  custom_config?: { [k: string]: any } | undefined;
};
