/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ReviewSnippet } from "./review-snippet.js";

/**
 * A place citation annotation.
 */
export type PlaceCitation = {
  /**
   * End of the attributed segment, exclusive.
   */
  end_index?: number | undefined;
  /**
   * Title of the place.
   */
  name?: string | undefined;
  /**
   * The ID of the place, in `places/{place_id}` format.
   */
  place_id?: string | undefined;
  /**
   * Snippets of reviews that are used to generate answers about the
   *
   * @remarks
   * features of a given place in Google Maps.
   */
  review_snippets?: Array<ReviewSnippet> | undefined;
  /**
   * Start of segment of the response that is attributed to this source.
   *
   * @remarks
   *
   * Index indicates the start of the segment, measured in bytes.
   */
  start_index?: number | undefined;
  type: "place_citation";
  /**
   * URI reference of the place.
   */
  url?: string | undefined;
};
