/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Streaming delta for a server-initiated media processing step.
 */
export type ProcessingCallDelta = {
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "processing_call";
};
