/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The definition of the Rag resource.
 */
export type RagResource = {
  /**
   * Optional. RagCorpora resource name.
   */
  rag_corpus?: string | undefined;
  /**
   * Optional. rag_file_id. The files should be in the same rag_corpus set in
   *
   * @remarks
   * rag_corpus field.
   */
  rag_file_ids?: Array<string> | undefined;
};
