/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Filter } from "./filter.js";
import { HybridSearch } from "./hybrid-search.js";
import { Ranking } from "./ranking.js";

/**
 * Specifies the context retrieval config.
 */
export type RagRetrievalConfig = {
  /**
   * Config for filters.
   */
  filter?: Filter | undefined;
  /**
   * Config for Hybrid Search.
   */
  hybrid_search?: HybridSearch | undefined;
  /**
   * Config for Rank Service.
   */
  ranking?: Ranking | undefined;
  /**
   * Optional. The number of contexts to retrieve.
   */
  top_k?: number | undefined;
};
