/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { RagResource } from "./rag-resource.js";
import { RagRetrievalConfig } from "./rag-retrieval-config.js";

/**
 * Use to specify configuration for RAG Store.
 */
export type RagStoreConfig = {
  /**
   * Optional. The representation of the rag source.
   */
  rag_resources?: Array<RagResource> | undefined;
  /**
   * Specifies the context retrieval config.
   */
  rag_retrieval_config?: RagRetrievalConfig | undefined;
  /**
   * Optional. Number of top k results to return from the selected corpora.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  similarity_top_k?: number | undefined;
  /**
   * Optional. Only return results with vector distance smaller than the threshold.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  vector_distance_threshold?: number | undefined;
};
