/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Config for Rank Service.
 */
export type Ranking = {
  /**
   * Optional. The model name of the rank service.
   */
  model_name?: string | undefined;
  ranking_config: "rank_service";
};
