/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AudioResponseFormat } from "./audio-response-format.js";
import { ImageResponseFormat } from "./image-response-format.js";
import { TextResponseFormat } from "./text-response-format.js";
import { VideoResponseFormat } from "./video-response-format.js";

export type ResponseFormat =
  | AudioResponseFormat
  | ImageResponseFormat
  | TextResponseFormat
  | VideoResponseFormat
  | { [k: string]: any };
