/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ExaAISearchConfig } from "./exa-ai-search-config.js";
import { ParallelAISearchConfig } from "./parallel-ai-search-config.js";
import { RagStoreConfig } from "./rag-store-config.js";
import { VertexAISearchConfig } from "./vertex-ai-search-config.js";

export type RetrievalRetrievalType =
  | "vertex_ai_search"
  | "rag_store"
  | "exa_ai_search"
  | "parallel_ai_search"
  | (string & {});

/**
 * A tool that can be used by the model to retrieve files.
 */
export type Retrieval = {
  /**
   * Used to specify configuration for ExaAISearch.
   */
  exa_ai_search_config?: ExaAISearchConfig | undefined;
  /**
   * Used to specify configuration for ParallelAISearch.
   */
  parallel_ai_search_config?: ParallelAISearchConfig | undefined;
  /**
   * Use to specify configuration for RAG Store.
   */
  rag_store_config?: RagStoreConfig | undefined;
  /**
   * The types of file retrieval to enable.
   */
  retrieval_types?: Array<RetrievalRetrievalType> | undefined;
  type: "retrieval";
  /**
   * Used to specify configuration for VertexAISearch.
   */
  vertex_ai_search_config?: VertexAISearchConfig | undefined;
};
