/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The arguments to pass to Retrieval tools.
 */
export type RetrievalCallArguments = {
  /**
   * Queries for Retrieval information.
   */
  queries?: Array<string> | undefined;
};
