/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { RetrievalCallArguments } from "./retrieval-call-arguments.js";

/**
 * The type of retrieval tools.
 */
export type RetrievalCallDeltaRetrievalType =
  | "vertex_ai_search"
  | "rag_store"
  | "exa_ai_search"
  | "parallel_ai_search"
  | (string & {});

/**
 * Used by Vertex Retrieval tools such as Parallel AI, Exa AI, Vertex AI Search,
 *
 * @remarks
 * etc. RetrievalType decides which tool is used.
 */
export type RetrievalCallDelta = {
  /**
   * The arguments to pass to Retrieval tools.
   */
  arguments: RetrievalCallArguments;
  /**
   * The type of retrieval tools.
   */
  retrieval_type?: RetrievalCallDeltaRetrievalType | undefined;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "retrieval_call";
};
