/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Encapsulates a snippet of a user review that answers a question about
 *
 * @remarks
 * the features of a specific place in Google Maps.
 */
export type ReviewSnippet = {
  /**
   * The ID of the review snippet.
   */
  review_id?: string | undefined;
  /**
   * Title of the review.
   */
  title?: string | undefined;
  /**
   * A link that corresponds to the user review on Google Maps.
   */
  url?: string | undefined;
};
