/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { HarmCategory } from "./harm-category.js";

/**
 * Optional. The method for blocking content. If not specified, the default
 *
 * @remarks
 * behavior is to use the probability score.
 */
export type Method = "severity" | "probability" | (string & {});

/**
 * Required. The threshold for blocking content. If the harm probability
 *
 * @remarks
 * exceeds this threshold, the content will be blocked.
 */
export type Threshold =
  | "block_low_and_above"
  | "block_medium_and_above"
  | "block_only_high"
  | "block_none"
  | "off"
  | (string & {});

/**
 * A safety setting that affects the safety-blocking behavior.
 *
 * @remarks
 *
 * A SafetySetting consists of a
 * harm category and a
 * threshold for that
 * category.
 */
export type SafetySetting = {
  /**
   * Optional. The method for blocking content. If not specified, the default
   *
   * @remarks
   * behavior is to use the probability score.
   */
  method?: Method | undefined;
  /**
   * Required. The threshold for blocking content. If the harm probability
   *
   * @remarks
   * exceeds this threshold, the content will be blocked.
   */
  threshold: Threshold;
  type: HarmCategory;
};
