/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The configuration of CodeMender sessions.
 */
export type SessionConfig = {
  /**
   * The maximum number of interaction rounds the agent is allowed to perform
   *
   * @remarks
   * before reaching a timeout.
   */
  max_rounds?: number | undefined;
};
