/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type SourceType =
  | "gcs"
  | "inline"
  | "repository"
  | "skill_registry"
  | (string & {});

/**
 * A source to be mounted into the environment.
 */
export type Source = {
  /**
   * The inline content if `type` is `INLINE`.
   */
  content?: string | undefined;
  /**
   * Optional encoding for inline content (e.g. `base64`).
   */
  encoding?: string | undefined;
  /**
   * The source of the environment.
   *
   * @remarks
   * For Cloud Storage, this is the Cloud Storage path.
   * For GitHub, this is the GitHub path.
   */
  source?: string | undefined;
  /**
   * Where the source should appear in the environment.
   */
  target?: string | undefined;
  type?: SourceType | undefined;
};
