/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SpeechConfig } from "./speech-config.js";

/**
 * Configuration for multi-speaker and speech generation.
 */
export type SpeakerConfig = {
  /**
   * Individual speaker configurations.
   */
  speakers?: Array<SpeechConfig> | undefined;
};
