/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The configuration for speech interaction.
 */
export type SpeechConfig = {
  /**
   * The language of the speech.
   */
  language?: string | undefined;
  /**
   * The speaker's name, it should match the speaker name given in the prompt.
   */
  speaker?: string | undefined;
  /**
   * The voice of the speaker.
   */
  voice?: string | undefined;
};
