/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type StaticMediaProcessing = {
  /**
   * Optional. Segment end time. Specified as a decimal number of seconds followed
   *
   * @remarks
   * by an 's' suffix, e.g., "30s". Must be non-negative and greater than
   * `start_offset` if `start_offset` is set.
   */
  end_offset?: string | undefined;
  /**
   * Optional. Video frame-rate sampling density.
   */
  fps?: number | undefined;
  /**
   * Optional. Segment start time. Specified as a decimal number of seconds followed
   *
   * @remarks
   * by an 's' suffix, e.g., "10.5s". Must be non-negative.
   */
  start_offset?: string | undefined;
  type: "static";
};
