/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CodeExecutionCallStep } from "./code-execution-call-step.js";
import { CodeExecutionResultStep } from "./code-execution-result-step.js";
import { FileSearchCallStep } from "./file-search-call-step.js";
import { FileSearchResultStep } from "./file-search-result-step.js";
import { FunctionCallStep } from "./function-call-step.js";
import { FunctionResultStep } from "./function-result-step.js";
import { GoogleMapsCallStep } from "./google-maps-call-step.js";
import { GoogleMapsResultStep } from "./google-maps-result-step.js";
import { GoogleSearchCallStep } from "./google-search-call-step.js";
import { GoogleSearchResultStep } from "./google-search-result-step.js";
import { MCPServerToolCallStep } from "./mcp-server-tool-call-step.js";
import { MCPServerToolResultStep } from "./mcp-server-tool-result-step.js";
import { ModelOutputStep } from "./model-output-step.js";
import { ProcessingCallStep } from "./processing-call-step.js";
import { ProcessingResultStep } from "./processing-result-step.js";
import { RetrievalCallStep } from "./retrieval-call-step.js";
import { RetrievalResultStep } from "./retrieval-result-step.js";
import { ThoughtStep } from "./thought-step.js";
import { URLContextCallStep } from "./url-context-call-step.js";
import { URLContextResultStep } from "./url-context-result-step.js";
import { UserInputStep } from "./user-input-step.js";

/**
 * A step in the interaction.
 */
export type Step =
  | CodeExecutionCallStep
  | CodeExecutionResultStep
  | FileSearchCallStep
  | FileSearchResultStep
  | FunctionCallStep
  | FunctionResultStep
  | GoogleMapsCallStep
  | GoogleMapsResultStep
  | GoogleSearchCallStep
  | GoogleSearchResultStep
  | MCPServerToolCallStep
  | MCPServerToolResultStep
  | ModelOutputStep
  | ProcessingCallStep
  | ProcessingResultStep
  | RetrievalCallStep
  | RetrievalResultStep
  | ThoughtStep
  | URLContextCallStep
  | URLContextResultStep
  | UserInputStep;
