/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { StepDeltaData } from "./step-delta-data.js";
import { StepDeltaMetadata } from "./step-delta-metadata.js";

export type StepDelta = {
  delta: StepDeltaData;
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "step.delta";
  index: number;
  /**
   * Optional metadata accompanying ANY streamed event.
   */
  metadata?: StepDeltaMetadata | undefined;
};
