/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Step } from "./step.js";

export type StepStart = {
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "step.start";
  index: number;
  /**
   * A step in the interaction.
   */
  step: Step;
};
