/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ArgumentsDelta } from "./arguments-delta.js";
import { AudioDelta } from "./audio-delta.js";
import { CodeExecutionCallDelta } from "./code-execution-call-delta.js";
import { CodeExecutionResultDelta } from "./code-execution-result-delta.js";
import { DocumentDelta } from "./document-delta.js";
import { FileSearchCallDelta } from "./file-search-call-delta.js";
import { FileSearchResultDelta } from "./file-search-result-delta.js";
import { FunctionResultDelta } from "./function-result-delta.js";
import { GoogleMapsCallDelta } from "./google-maps-call-delta.js";
import { GoogleMapsResultDelta } from "./google-maps-result-delta.js";
import { GoogleSearchCallDelta } from "./google-search-call-delta.js";
import { GoogleSearchResultDelta } from "./google-search-result-delta.js";
import { ImageDelta } from "./image-delta.js";
import { MCPServerToolCallDelta } from "./mcp-server-tool-call-delta.js";
import { MCPServerToolResultDelta } from "./mcp-server-tool-result-delta.js";
import { ProcessingCallDelta } from "./processing-call-delta.js";
import { ProcessingResultDelta } from "./processing-result-delta.js";
import { RetrievalCallDelta } from "./retrieval-call-delta.js";
import { RetrievalResultDelta } from "./retrieval-result-delta.js";
import { TextAnnotationDelta } from "./text-annotation-delta.js";
import { TextDelta } from "./text-delta.js";
import { ThoughtSignatureDelta } from "./thought-signature-delta.js";
import { ThoughtSummaryDelta } from "./thought-summary-delta.js";
import { URLContextCallDelta } from "./url-context-call-delta.js";
import { URLContextResultDelta } from "./url-context-result-delta.js";
import { VideoDelta } from "./video-delta.js";

export type StepDeltaData =
  | ArgumentsDelta
  | AudioDelta
  | CodeExecutionCallDelta
  | CodeExecutionResultDelta
  | DocumentDelta
  | FileSearchCallDelta
  | FileSearchResultDelta
  | FunctionResultDelta
  | GoogleMapsCallDelta
  | GoogleMapsResultDelta
  | GoogleSearchCallDelta
  | GoogleSearchResultDelta
  | ImageDelta
  | MCPServerToolCallDelta
  | MCPServerToolResultDelta
  | ProcessingCallDelta
  | ProcessingResultDelta
  | RetrievalCallDelta
  | RetrievalResultDelta
  | TextAnnotationDelta
  | TextDelta
  | ThoughtSignatureDelta
  | ThoughtSummaryDelta
  | URLContextCallDelta
  | URLContextResultDelta
  | VideoDelta;
