/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Usage } from "./usage.js";

/**
 * Optional metadata accompanying ANY streamed event.
 */
export type StepDeltaMetadata = {
  /**
   * Statistics on the interaction request's token usage.
   */
  total_usage?: Usage | undefined;
};
