/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Annotation } from "./annotation.js";

export type TextAnnotationDelta = {
  /**
   * Citation information for model-generated content.
   */
  annotations?: Array<Annotation> | undefined;
  type: "text_annotation_delta";
};
