/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The MIME type of the text output.
 */
export type TextResponseFormatMimeType =
  | "application/json"
  | "text/plain"
  | (string & {});

/**
 * Configuration for text output format.
 */
export type TextResponseFormat = {
  /**
   * The MIME type of the text output.
   */
  mime_type?: TextResponseFormatMimeType | undefined;
  /**
   * The JSON schema that the output should conform to. Only applicable when
   *
   * @remarks
   * mime_type is application/json.
   */
  schema?: { [k: string]: any } | undefined;
  type: "text";
};
