/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Content } from "./content.js";

export type ThoughtSummaryDelta = {
  /**
   * The content of the response.
   */
  content?: Content | undefined;
  type: "thought_summary";
};
