/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ImageContent } from "./image-content.js";
import { TextContent } from "./text-content.js";

export type ThoughtSummaryContent = ImageContent | TextContent;
