/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ThoughtSummaryContent } from "./thought-summary-content.js";

/**
 * A thought step.
 */
export type ThoughtStep = {
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  /**
   * A summary of the thought.
   */
  summary?: Array<ThoughtSummaryContent> | undefined;
  type: "thought";
};
