/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ThoughtSignatureDelta = {
  /**
   * Signature to match the backend source to be part of the generation.
   */
  signature?: string | undefined;
  type: "thought_signature";
};
