/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CodeExecution } from "./code-execution.js";
import { ComputerUse } from "./computer-use.js";
import { FileSearch } from "./file-search.js";
import { FunctionT } from "./function.js";
import { GoogleMaps } from "./google-maps.js";
import { GoogleSearch } from "./google-search.js";
import { MCPServer } from "./mcp-server.js";
import { Retrieval } from "./retrieval.js";
import { URLContext } from "./url-context.js";

/**
 * A tool that can be used by the model.
 */
export type Tool =
  | CodeExecution
  | ComputerUse
  | FileSearch
  | FunctionT
  | GoogleMaps
  | GoogleSearch
  | MCPServer
  | Retrieval
  | URLContext;
