/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AllowedTools } from "./allowed-tools.js";

/**
 * The tool choice configuration containing allowed tools.
 */
export type ToolChoiceConfig = {
  /**
   * The configuration for allowed tools.
   */
  allowed_tools?: AllowedTools | undefined;
};
