/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { TranscriptionMode } from "./transcription-mode.js";

export type TranscriptionConfigModeEnum = "verbatim" | "smart" | (string & {});

/**
 * Discriminated transcription mode options or enum.
 */
export type TranscriptionConfigMode =
  | TranscriptionMode
  | TranscriptionConfigModeEnum;

/**
 * Configuration for speech recognition (transcription).
 */
export type TranscriptionConfig = {
  /**
   * Optional. A list of phrases to bias the ASR model towards.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  adaptation_phrases?: Array<string> | undefined;
  /**
   * Optional. A list of custom vocabulary phrases to bias the speech recognition model
   *
   * @remarks
   * toward recognizing specific terms.
   */
  custom_vocabulary?: Array<string> | undefined;
  /**
   * Optional. Configures speaker diarization. Supported values: "speaker".
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  diarization_mode?: string | undefined;
  /**
   * Optional. BCP-47 language codes providing hints about the languages present in the
   *
   * @remarks
   * audio. If omitted or empty, defaults to automatic language detection.
   */
  language_codes?: Array<string> | undefined;
  /**
   * Discriminated transcription mode options or enum.
   */
  mode?: TranscriptionMode | TranscriptionConfigModeEnum | undefined;
  /**
   * Optional. The granularity of timestamps to include in the transcription output.
   *
   * @remarks
   * Supported values: "word". If empty, no timestamps are generated.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  timestamp_granularities?: Array<string> | undefined;
};
