/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SmartTranscriptionMode } from "./smart-transcription-mode.js";
import { VerbatimTranscriptionMode } from "./verbatim-transcription-mode.js";

/**
 * Configuration for transcription mode.
 */
export type TranscriptionMode =
  | SmartTranscriptionMode
  | VerbatimTranscriptionMode;
