/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A URL citation annotation.
 */
export type URLCitation = {
  /**
   * End of the attributed segment, exclusive.
   */
  end_index?: number | undefined;
  /**
   * Start of segment of the response that is attributed to this source.
   *
   * @remarks
   *
   * Index indicates the start of the segment, measured in bytes.
   */
  start_index?: number | undefined;
  /**
   * The title of the URL.
   */
  title?: string | undefined;
  type: "url_citation";
  /**
   * The URL.
   */
  url?: string | undefined;
};
