/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { URLContextCallArguments } from "./url-context-call-arguments.js";

/**
 * URL context call step.
 */
export type URLContextCallStep = {
  /**
   * The arguments to pass to the URL context.
   */
  arguments: URLContextCallArguments;
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "url_context_call";
};
