/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { URLContextCallArguments } from "./url-context-call-arguments.js";

export type URLContextCallDelta = {
  /**
   * The arguments to pass to the URL context.
   */
  arguments: URLContextCallArguments;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "url_context_call";
};
