/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A tool that can be used by the model to fetch URL context.
 */
export type URLContext = {
  type: "url_context";
};
