/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The arguments to pass to the URL context.
 */
export type URLContextCallArguments = {
  /**
   * The URLs to fetch.
   */
  urls?: Array<string> | undefined;
};
