/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GroundingToolCount } from "./grounding-tool-count.js";
import { ModalityTokens } from "./modality-tokens.js";

/**
 * Statistics on the interaction request's token usage.
 */
export type Usage = {
  /**
   * A breakdown of cached token usage by modality.
   */
  cached_tokens_by_modality?: Array<ModalityTokens> | undefined;
  /**
   * Grounding tool count.
   */
  grounding_tool_count?: Array<GroundingToolCount> | undefined;
  /**
   * A breakdown of input token usage by modality.
   */
  input_tokens_by_modality?: Array<ModalityTokens> | undefined;
  /**
   * A breakdown of output token usage by modality.
   */
  output_tokens_by_modality?: Array<ModalityTokens> | undefined;
  /**
   * A breakdown of tool-use token usage by modality.
   */
  tool_use_tokens_by_modality?: Array<ModalityTokens> | undefined;
  /**
   * Number of tokens in the cached part of the prompt (the cached content).
   */
  total_cached_tokens?: number | undefined;
  /**
   * Number of tokens in the prompt (context).
   */
  total_input_tokens?: number | undefined;
  /**
   * Total number of tokens across all the generated responses.
   */
  total_output_tokens?: number | undefined;
  /**
   * Number of tokens of thoughts for thinking models.
   */
  total_thought_tokens?: number | undefined;
  /**
   * Total token count for the interaction request (prompt + responses + other
   *
   * @remarks
   * internal tokens).
   */
  total_tokens?: number | undefined;
  /**
   * Number of tokens present in tool-use prompt(s).
   */
  total_tool_use_tokens?: number | undefined;
};
