/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Content } from "./content.js";

/**
 * Input provided by the user.
 */
export type UserInputStep = {
  content?: Array<Content> | undefined;
  type: "user_input";
};
