/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for verbatim transcription mode.
 */
export type VerbatimTranscriptionMode = {
  /**
   * Optional. Configures speaker diarization. Supported values: "speaker".
   */
  diarization_mode?: string | undefined;
  /**
   * Optional. The granularity of timestamps to include in the transcription output.
   *
   * @remarks
   * Supported values: "word". If empty, no timestamps are generated.
   */
  timestamp_granularities?: Array<string> | undefined;
  type: "verbatim";
};
