/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Used to specify configuration for VertexAISearch.
 */
export type VertexAISearchConfig = {
  /**
   * Optional. Used to specify Vertex AI Search datastores.
   */
  datastores?: Array<string> | undefined;
  /**
   * Optional. Used to specify Vertex AI Search engine.
   */
  engine?: string | undefined;
};
