/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Optional task mode for video generation. If not specified, the model
 *
 * @remarks
 * automatically determines the appropriate mode based on the provided text
 * prompt and input media.
 */
export type Task =
  | "text_to_video"
  | "image_to_video"
  | "reference_to_video"
  | "edit"
  | "extend"
  | (string & {});

/**
 * Configuration options for video generation.
 */
export type VideoConfig = {
  /**
   * Optional task mode for video generation. If not specified, the model
   *
   * @remarks
   * automatically determines the appropriate mode based on the provided text
   * prompt and input media.
   */
  task?: Task | undefined;
};
