/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { MediaResolution } from "./media-resolution.js";

export type VideoDeltaMimeType =
  | "video/mp4"
  | "video/mpeg"
  | "video/mpg"
  | "video/mov"
  | "video/avi"
  | "video/x-flv"
  | "video/webm"
  | "video/wmv"
  | "video/3gpp"
  | "video/jpeg2000"
  | (string & {});

export type VideoDelta = {
  data?: string | undefined;
  mime_type?: VideoDeltaMimeType | undefined;
  resolution?: MediaResolution | undefined;
  type: "video";
  uri?: string | undefined;
};
