/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { MediaProcessing } from "./media-processing.js";
import { MediaResolution } from "./media-resolution.js";

/**
 * The mime type of the video.
 */
export type VideoContentMimeType =
  | "video/mp4"
  | "video/mpeg"
  | "video/mpg"
  | "video/mov"
  | "video/avi"
  | "video/x-flv"
  | "video/webm"
  | "video/wmv"
  | "video/3gpp"
  | (string & {});

export type ProcessingEnum = "static" | "agentic" | (string & {});

/**
 * How the model processes this video for understanding.
 */
export type Processing = MediaProcessing | ProcessingEnum;

/**
 * A video content block.
 */
export type VideoContent = {
  /**
   * The video content.
   */
  data?: string | undefined;
  /**
   * The mime type of the video.
   */
  mime_type?: VideoContentMimeType | undefined;
  /**
   * A user-defined name for this content block. Can be referenced by the model
   *
   * @remarks
   * in the final response.
   */
  name?: string | undefined;
  /**
   * How the model processes this video for understanding.
   */
  processing?: MediaProcessing | ProcessingEnum | undefined;
  resolution?: MediaResolution | undefined;
  type: "video";
  /**
   * The URI of the video.
   */
  uri?: string | undefined;
};
