/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Message for configuring webhook events for a request.
 */
export type WebhookConfig = {
  /**
   * Optional. If set, these webhook URIs will be used for webhook events instead of the
   *
   * @remarks
   * registered webhooks.
   */
  uris?: Array<string> | undefined;
  /**
   * Optional. The user metadata that will be returned on each event emission to the
   *
   * @remarks
   * webhooks.
   */
  user_metadata?: { [k: string]: any } | undefined;
};
