/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Word-level ASR annotation for transcription output.
 *
 * @remarks
 * Carries the word text, optional timing, and optional speaker attribution.
 */
export type WordInfo = {
  /**
   * End of the attributed segment, exclusive.
   */
  end_index?: number | undefined;
  /**
   * End offset in time of the word relative to the start of the audio.
   *
   * @remarks
   * Present when timestamp_granularities contains "word".
   */
  end_offset?: string | undefined;
  /**
   * Optional. Speaker label for this word (e.g. "spk_1", "spk_2").
   *
   * @remarks
   * Present when diarization_mode is set in TranscriptionConfig.
   */
  speaker?: string | undefined;
  /**
   * Start of segment of the response that is attributed to this source.
   *
   * @remarks
   *
   * Index indicates the start of the segment, measured in bytes.
   */
  start_index?: number | undefined;
  /**
   * Start offset in time of the word relative to the start of the audio.
   *
   * @remarks
   * Present when timestamp_granularities contains "word".
   */
  start_offset?: string | undefined;
  /**
   * The transcribed word.
   */
  text?: string | undefined;
  type: "word_info";
};
