/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Optional. The revocation behavior for previous signing secrets.
 */
export type RevocationBehavior =
  | "revoke_previous_secrets_after_h24"
  | "revoke_previous_secrets_immediately";

/**
 * Request message for WebhookService.RotateSigningSecret.
 */
export type RotateSigningSecretRequest = {
  /**
   * Optional. The revocation behavior for previous signing secrets.
   */
  revocation_behavior?: RevocationBehavior | undefined;
};
