/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Represents a signing secret used to verify webhook payloads.
 */
export type SigningSecret = {
  /**
   * Output only. The expiration date of the signing secret.
   */
  expire_time?: string | undefined;
  /**
   * Output only. The truncated version of the signing secret.
   */
  truncated_secret?: string | undefined;
};
