/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SigningSecret } from "./signing-secret.js";

/**
 * Output only. The state of the webhook.
 */
export type WebhookState =
  | "enabled"
  | "disabled"
  | "disabled_due_to_failed_deliveries"
  | (string & {});

export type WebhookSubscribedEvent =
  | "batch.succeeded"
  | "batch.expired"
  | "batch.failed"
  | "interaction.requires_action"
  | "interaction.completed"
  | "interaction.failed"
  | "video.generated"
  | (string & {});

/**
 * A Webhook resource.
 */
export type Webhook = {
  /**
   * Output only. The timestamp when the webhook was created.
   */
  create_time?: string | undefined;
  /**
   * Output only. The ID of the webhook.
   */
  id?: string | undefined;
  /**
   * Optional. The user-provided name of the webhook.
   */
  name?: string | undefined;
  /**
   * Output only. The new signing secret for the webhook. Only populated on create.
   */
  new_signing_secret?: string | undefined;
  /**
   * Output only. The signing secrets associated with this webhook.
   */
  signing_secrets?: Array<SigningSecret> | undefined;
  /**
   * Output only. The state of the webhook.
   */
  state?: WebhookState | undefined;
  /**
   * Required. The events that the webhook is subscribed to.
   *
   * @remarks
   * Available events:
   * - batch.succeeded
   * - batch.expired
   * - batch.failed
   * - interaction.requires_action
   * - interaction.completed
   * - interaction.failed
   * - video.generated
   */
  subscribed_events: Array<WebhookSubscribedEvent>;
  /**
   * Output only. The timestamp when the webhook was last updated.
   */
  update_time?: string | undefined;
  /**
   * Required. The URI to which webhook events will be sent.
   */
  uri: string;
};

/**
 * A Webhook resource.
 */
export type WebhookInput = {
  /**
   * Optional. The user-provided name of the webhook.
   */
  name?: string | undefined;
  /**
   * Required. The events that the webhook is subscribed to.
   *
   * @remarks
   * Available events:
   * - batch.succeeded
   * - batch.expired
   * - batch.failed
   * - interaction.requires_action
   * - interaction.completed
   * - interaction.failed
   * - video.generated
   */
  subscribed_events: Array<WebhookSubscribedEvent>;
  /**
   * Required. The URI to which webhook events will be sent.
   */
  uri: string;
};
