/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Response message for WebhookService.RotateSigningSecret.
 */
export type WebhookRotateSigningSecretResponse = {
  /**
   * Output only. The newly generated signing secret.
   */
  secret?: string | undefined;
};
