/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Optional. The state of the webhook.
 */
export type WebhookUpdateState =
  | "enabled"
  | "disabled"
  | "disabled_due_to_failed_deliveries";

export type WebhookUpdateSubscribedEvent =
  | "batch.succeeded"
  | "batch.expired"
  | "batch.failed"
  | "interaction.requires_action"
  | "interaction.completed"
  | "interaction.failed"
  | "video.generated"
  | (string & {});

export type WebhookUpdate = {
  /**
   * Optional. The user-provided name of the webhook.
   */
  name?: string | undefined;
  /**
   * Optional. The state of the webhook.
   */
  state?: WebhookUpdateState | undefined;
  /**
   * Optional. The events that the webhook is subscribed to.
   *
   * @remarks
   * Available events:
   * - batch.succeeded
   * - batch.expired
   * - batch.failed
   * - interaction.requires_action
   * - interaction.completed
   * - interaction.failed
   * - video.generated
   */
  subscribed_events?: Array<WebhookUpdateSubscribedEvent> | undefined;
  /**
   * Optional. The URI to which webhook events will be sent.
   */
  uri?: string | undefined;
};
