/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Webhook } from "./webhook.js";

/**
 * Response message for WebhookService.ListWebhooks.
 */
export type WebhookListResponse = {
  /**
   * A token, which can be sent as `page_token` to retrieve the next page.
   *
   * @remarks
   * If this field is omitted, there are no subsequent pages.
   */
  next_page_token?: string | undefined;
  /**
   * The webhooks.
   */
  webhooks?: Array<Webhook> | undefined;
};
