/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";
import { AgentTool } from "./agent-tool.js";

/**
 * Configuration parameters for the agent.
 */
export type AgentConfig = interactions.AntigravityAgentConfig;

/**
 * The environment configuration for the agent.
 */
export type BaseEnvironment = interactions.Environment | string;

/**
 * An agent definition for the CreateAgent API.
 *
 * @remarks
 * This message is the target for annotation-parser-based JSON parsing.
 * New format:
 *   {
 *     "id": "customer-sentinel",
 *     "base_agent": "",
 *     "system_instruction": "...",
 *     "base_environment": { "type": "remote", "sources": [...] },
 *     "tools": [ {"type": "code_execution"} ]
 *   }
 */
export type Agent = {
  /**
   * Configuration parameters for the agent.
   */
  agent_config?: interactions.AntigravityAgentConfig | undefined;
  /**
   * The base agent to extend.
   */
  base_agent?: string | undefined;
  /**
   * The environment configuration for the agent.
   */
  base_environment?: interactions.Environment | string | undefined;
  /**
   * Agent description for developers to quickly read and understand.
   */
  description?: string | undefined;
  /**
   * The unique identifier for the agent.
   */
  id?: string | undefined;
  /**
   * System instruction for the agent.
   */
  system_instruction?: string | undefined;
  /**
   * The tools available to the agent.
   */
  tools?: Array<AgentTool> | undefined;
};
