/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Agent } from "./agent.js";

export type AgentListResponse = {
  agents?: Array<Agent> | undefined;
  next_page_token?: string | undefined;
};
