/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

/**
 * A tool that the agent can use.
 */
export type AgentTool =
  | interactions.CodeExecution
  | interactions.FunctionT
  | interactions.GoogleSearch
  | interactions.MCPServer
  | interactions.URLContext;
