/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

export type CreateEnvironmentRequestNetworkEnum = "disabled";

/**
 * Network configuration for the environment.
 */
export type CreateEnvironmentRequestNetworkUnion =
  | interactions.EnvironmentNetworkEgressAllowlist
  | CreateEnvironmentRequestNetworkEnum;

/**
 * Request for `CreateEnvironment`.
 */
export type CreateEnvironmentRequest = {
  /**
   * Optional. The source environment to copy/fork from.
   *
   * @remarks
   * Format: `environments/{environment_id}` or `{environment_id}`.
   * When specified, `sources` and `env` must be empty.
   */
  from_environment?: string | undefined;
  /**
   * Network configuration for the environment.
   */
  network?:
    | interactions.EnvironmentNetworkEgressAllowlist
    | CreateEnvironmentRequestNetworkEnum
    | undefined;
  /**
   * Sources to be mounted into the environment.
   */
  sources?: Array<interactions.Source> | undefined;
};
