/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Output only. The type of the entry.
 */
export type Type = "file" | "directory" | (string & {});

/**
 * Metadata for a file or directory within an environment.
 */
export type EnvironmentFile = {
  /**
   * Output only. The creation time of the file/directory.
   */
  created?: string | undefined;
  /**
   * Output only. The MIME type of the file (e.g., "text/python", "image/png").
   *
   * @remarks
   * Empty for directories.
   * NOLINT
   */
  mime_type?: string | undefined;
  /**
   * Output only. The modification time of the file/directory.
   */
  modified?: string | undefined;
  /**
   * Output only. The name of the file or directory (e.g., "main.py" or "src").
   */
  name?: string | undefined;
  /**
   * Output only. The full relative path within the environment
   *
   * @remarks
   * (e.g., "workspace/src/main.py").
   */
  path?: string | undefined;
  /**
   * Output only. The size of the file/directory in bytes.
   *
   * @remarks
   * NOLINT
   */
  size_bytes?: string | undefined;
  /**
   * Output only. The type of the entry.
   */
  type?: Type | undefined;
};
