/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EnvironmentFile } from "./environment-file.js";

/**
 * Response for `GetEnvironmentFiles`.
 */
export type GetEnvironmentFilesResponse = {
  /**
   * If the requested path is a directory, this contains its contents.
   *
   * @remarks
   * If the requested path is a file, this contains a single entry with the
   * file's metadata.
   * If alt=media was specified, this is empty (content is served via `blob`).
   */
  files?: Array<EnvironmentFile> | undefined;
  /**
   * Pagination token for directory listing.
   *
   * @remarks
   * NOLINT
   */
  next_page_token?: string | undefined;
};
