/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Environment } from "./environment.js";

/**
 * Response for `ListEnvironments`.
 */
export type ListEnvironmentsResponse = {
  /**
   * Environments belonging to the provided project.
   */
  environments?: Array<Environment> | undefined;
  /**
   * Pagination token.
   */
  next_page_token?: string | undefined;
};
